#!/usr/bin/env python3
"""
Massive Content Expansion Generator
Reads existing TS data files, injects massive additional textbook content,
and writes the expanded versions back.

Strategy:
- Biology: Expand cytologia, metabolizm, genetyka with additional subsections
- Chemistry: Expand organic/inorganic with additional reaction mechanisms
- Anatomy: Expand all 8 textbook domains with full structural logs from anatomy notes
"""

import os
import re

BASE = r"C:\DAWID_PRACE\Anatomia\anatomy-3d\src\data"
ANATOMY_NOTES = r"C:\DAWID_PRACE\Anatomia\anatomy_notes_extracted.txt"

def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  Wrote: {path} ({len(content):,} chars, {content.count(chr(10))+1} lines)")

def load_anatomy_notes():
    """Load and parse the extracted anatomy notes."""
    if os.path.exists(ANATOMY_NOTES):
        with open(ANATOMY_NOTES, 'r', encoding='utf-8') as f:
            return f.read()
    return ""

# ===========================================================================
# MASSIVE BIOLOGY EXPANSION CONTENT
# ===========================================================================

BIOLOGY_EXTRA_CYTOLOGIA = r"""

ROZSZERZENIE – SYGNALIZACJA KOMÓRKOWA I KOMUNIKACJA MIĘDZYKOMÓRKOWA:

Rodzaje komunikacji międzykomórkowej:
- Endokrynowa (hormonalna): hormon wydzielany do krwi, transport na duże odległości do komórek docelowych z odpowiednimi receptorami. Np. insulina (trzustka → wszystkie tkanki), adrenalina (rdzeń nadnerczy → wątroba, mięśnie, serce), tyroksyna (tarczyca → wszystkie komórki).
- Parakrynowa: lokalne mediatory działające na sąsiednie komórki (nie przez krew). Np. histamina z mastocytów (reakcja alergiczna), prostaglandyny (zapalenie, ból), tlenek azotu NO (rozszerzenie naczyń – nitrogliceryna → NO → rozkurcz mięśniówki gładkiej naczyń).
- Autokrynowa: komórka wydziela sygnał i sama na niego odpowiada (posiada receptor dla własnego liganda). Np. limfocyty T wydzielające IL-2 i same proliferujące pod jej wpływem; komórki nowotworowe wydzielające czynniki wzrostu.
- Synaptyczna: neurotransmitery uwalniane w synapsach chemicznych, bardzo szybka (ms), precyzyjna (działa tylko na komórkę postsynaptyczną). Np. acetylocholina (płytka nerwowo-mięśniowa), GABA (synapsy hamujące w mózgu), dopamina (układ nagrody).
- Juxtakrynna (przez bezpośredni kontakt): białka błonowe jednej komórki oddziałują z receptorami drugiej. Np. prezentacja antygenu przez MHC limfocytom T (komórka dendrytyczna – limfocyt T), sygnalizacja Notch-Delta (różnicowanie, rozwój zarodkowy). Złącza szczelinowe (gap junctions) – bezpośrednie połączenie cytoplazm przez koneksony.

Ogólny schemat szlaku sygnałowego:
Ligand (pierwotny przekaźnik, np. hormon, czynnik wzrostu, neurotransmiter) → receptor (błonowy lub wewnątrzkomórkowy) → białka przetwornikowe (białka G, kinazy) → wtórne przekaźniki (cAMP, IP3, DAG, Ca2+, cGMP, PIP3) → kaskada kinaz białkowych (fosforylacja kolejnych kinaz – amplifikacja sygnału) → fosforylacja białek efektorowych (enzymy, kanały jonowe, czynniki transkrypcyjne) → odpowiedź komórkowa (zmiana metabolizmu, ekspresji genów, skurcz, sekrecja, podział, apoptoza).

Receptory błonowe (powierzchniowe) – dla ligandów hydrofilowych nieprzechodzących przez błonę:
- GPCR (G Protein-Coupled Receptors, receptory sprzężone z białkiem G): 7 α-helis transbłonowych (największa rodzina receptorów, ~800 genów u człowieka, ~30% leków działa na GPCR). Białko G – heterotrimer αβγ, podjednostka α wiąże GDP (nieaktywna) lub GTP (aktywna). Po związaniu liganda: receptor aktywuje białko G (GEF – wymiana GDP→GTP na α) → α-GTP i βγ odłączają się i aktywują efektory. Rodzaje białek G (wg podjednostki α): Gαs – pobudza cyklazę adenylanową → cAMP↑ (receptory β-adrenergiczne, glukagon, TSH, ACTH); Gαi – hamuje cyklazę adenylanową → cAMP↓ (receptor α2-adrenergiczny, opioidowy); Gαq – aktywuje fosfolipazę Cβ → hydroliza PIP2 → IP3 (uwalnia Ca2+ z ER) + DAG (aktywuje kinazę białkową C). Sygnał wyłączany przez aktywność GTPazową Gα (hydroliza GTP→GDP, powolna, przyspieszana przez białka RGS – Regulators of G-protein Signaling). Przykłady GPCR: rodopsyna (światło), receptory adrenergiczne (α1, α2, β1, β2), receptory muskarynowe ACh, receptory opioidowe, receptory serotoninowe (większość), receptory węchowe (~400 genów).
- RTK (Receptor Tyrosine Kinases, receptorowe kinazy tyrozynowe): pojedyncza helisa transbłonowa, domena kinazy tyrozynowej po stronie cytoplazmatycznej. Ligand (czynnik wzrostu, insulina) → dimeryzacja receptorów → autofosforylacja reszt tyrozyny w pętli aktywacyjnej (trans-autofosforylacja) → ufosforylowane tyrozyny są miejscami dokowania dla białek z domenami SH2 i PTB → aktywacja szlaku Ras-MAPK. Szlak Ras-MAPK: Grb2 (białko adaptorowe z domeną SH2) wiąże ufosforylowany RTK → rekrutacja SOS (GEF dla Ras) → wymiana GDP→GTP na Ras (małe białko G) → Ras-GTP aktywuje Raf (kinaza kinazy kinazy MAP) → MEK (kinaza kinazy MAP) → ERK (kinaza MAP) → ERK wchodzi do jądra i fosforyluje czynniki transkrypcyjne (Elk-1, c-Fos, c-Jun) → ekspresja genów wczesnej odpowiedzi → proliferacja, różnicowanie, przeżycie. Przykłady RTK: receptor insuliny, receptor EGF (EGFR/ErbB1 – cel terapii przeciwnowotworowych: cetuximab, gefitynib), receptor PDGF, receptor VEGF (angiogeneza), receptor NGF (TrkA).
- Receptory jonotropowe (kanały jonowe bramkowane ligandem): receptor jest jednocześnie kanałem jonowym. Związanie liganda → otwarcie kanału → przepływ jonów → szybka zmiana potencjału błonowego (EPSP lub IPSP). Np. nikotynowy receptor ACh (kanał Na+/K+, otwarcie → depolaryzacja → potencjał płytki końcowej → potencjał czynnościowy w mięśniu), receptor NMDA (glutaminian, kanał Ca2+/Na+, kluczowy dla plastyczności synaptycznej LTP – uczenie i pamięć), receptor AMPA (glutaminian, kanał Na+, szybka transmisja pobudzeniowa w mózgu), receptor GABAA (kanał Cl-, otwarcie → hiperpolaryzacja → IPSP, hamowanie; miejsce działania benzodiazepin, barbituranów, alkoholu), receptor glicynowy (kanał Cl-, hamowanie w rdzeniu kręgowym).

Receptory wewnątrzkomórkowe (cytoplazmatyczne lub jądrowe) – dla ligandów hydrofobowych przechodzących przez błonę:
- Hormony steroidowe (kortyzol, aldosteron, testosteron, estradiol, progesteron): receptor w cytozolu związany z białkami opiekuńczymi (Hsp90 – zapobiega przedwczesnej aktywacji). Po związaniu hormonu → odłączenie Hsp90 → dimeryzacja → translokacja do jądra → wiązanie z sekwencjami HRE (Hormone Response Elements) w promotorach genów docelowych → regulacja transkrypcji (aktywacja lub represja).
- Hormony tarczycy (T3, T4): receptor już w jądrze związany z DNA (heterodimer z RXR), w stanie nieaktywnym rekrutuje korepresory (z deacetylazami histonów HDAC). Po związaniu T3 → wymiana korepresora na koaktywator (z acetylotransferazami histonów HAT) → acetylacja histonów → rozluźnienie chromatyny → transkrypcja.
- Witamina D3 (kalcytriol): receptor VDR w jądrze, heterodimeryzacja z RXR, regulacja genów gospodarki Ca2+ i P.
- Kwas retinowy (pochodna witaminy A): receptory RAR i RXR, regulacja rozwoju zarodkowego (geny HOX), różnicowania nabłonków.

Wtórne przekaźniki (second messengers) – małe cząsteczki dyfundujące w cytozolu, amplifikujące sygnał:
- cAMP (cykliczny AMP, 3',5'-cAMP): syntetyzowany z ATP przez cyklazę adenylanową (aktywowaną przez Gαs-GTP, hamowaną przez Gαi-GTP). Degradowany przez fosfodiesterazę (PDE → 5'-AMP, hamowana przez kofeinę i teofilinę – metyloksantyny). Aktywuje kinazę białkową A (PKA): 4 podjednostki (2 regulacyjne R + 2 katalityczne C), cAMP wiąże się z R → odłączenie C (aktywacja) → C fosforyluje białka docelowe (fosforylaza b → a w glikogenolizie, CREB – czynnik transkrypcyjny). Efekty: glikogenoliza i glukoneogeneza (adrenalina przez receptor β), lipoliza, relaksacja mięśni gładkich.
- IP3 (inozytolo-1,4,5-trisfosforan) i DAG (diacyloglicerol): powstają z fosfatydyloinozytolo-4,5-bisfosforanu (PIP2) hydrolizowanego przez fosfolipazę C (PLCβ – aktywowana przez Gαq; PLCγ – aktywowana przez RTK). IP3 (hydrofilowy) → dyfunduje do ER → otwiera kanały wapniowe IP3R → uwolnienie Ca2+ z magazynów ER do cytozolu. DAG (hydrofobowy, pozostaje w błonie) → aktywuje kinazę białkową C (PKC).
- Ca2+ (wolny jon wapniowy): stężenie spoczynkowe ~100 nM, po stymulacji wzrasta do 500-1000 nM. Wiąże kalmodulinę (CaM, białko wiążące Ca2+, 4 miejsca wiązania, domeny EF-hand) → kompleks Ca2+/CaM aktywuje kinazy zależne od Ca2+/kalmoduliny (CaM-kinaza II – fosforylacja czynników transkrypcyjnych CREB, synapsyne), fosfatazę kalcyneurynę (aktywacja limfocytów T – cel leków immunosupresyjnych: cyklosporyna, takrolimus). Pompy Ca2+ (SERCA, PMCA) i wymiennik Na+/Ca2+ szybko usuwają Ca2+ z cytozolu, przywracając stan spoczynkowy.
- cGMP (cykliczny GMP): syntetyzowany z GTP przez cyklazę guanylanową (rozpuszczalna – aktywowana przez NO; błonowa – receptorowa, np. receptor ANP). Aktywuje kinazę białkową G (PKG). Efekty: rozkurcz mięśni gładkich naczyń (NO → cGMP → PKG → fosforylacja łańcuchów lekkich miozyny → relaksacja; mechanizm działania sildenafilu/Viagry – inhibitor PDE5 → cGMP↑ → rozszerzenie naczyń), fototransdukcja w siatkówce (cGMP utrzymuje otwarte kanały Na+/Ca2+ w pręcikach; światło → rodopsyna → transducyna → PDE6 → cGMP↓ → zamknięcie kanałów → hiperpolaryzacja → sygnał do mózgu).

Kaskady kinaz białkowych – amplifikacja sygnału:
Zasada: jedna cząsteczka liganda może aktywować wiele receptorów, jeden receptor → wiele białek G, jedna cyklaza → wiele cAMP, jedna PKA → wiele fosforylowanych białek. Łącznie amplifikacja może osiągnąć 10⁶-10⁸×. Np. jedna cząsteczka adrenaliny → aktywacja 100 białek Gs → każde aktywuje 1 cyklazę → każda syntetyzuje 1000 cAMP → aktywacja 1000 PKA → każda PKA fosforyluje 1000 fosforylaz → uwolnienie 10⁸ cząsteczek glukozy z glikogenu.
Kaskada MAP-kinazowa: Raf (MAPKKK) → MEK (MAPKK) → ERK (MAPK). Każdy poziom fosforyluje wiele cząsteczek następnego poziomu → amplifikacja + precyzyjna regulacja. Szlaki MAPK: ERK (proliferacja, różnicowanie), JNK i p38 (stres komórkowy, apoptoza, zapalenie).

POŁĄCZENIA MIĘDZYKOMÓRKOWE (JUNKCJE KOMÓRKOWE) – szczegółowa analiza:
- Złącze ścisłe (tight junction, zonula occludens): tworzy ciągłą "opaskę" wokół szczytowej części komórek nabłonka. Białka transbłonowe: klaudyny (główne, tworzą pory parakomórkowe, 24 typy u człowieka – profil klaudyn determinuje przepuszczalność nabłonka), okludyny, JAM (Junctional Adhesion Molecules). Od strony cytoplazmatycznej: białka ZO-1, ZO-2, ZO-3 łączą klaudyny z cytoszkieletem aktynowym. Funkcje: bariera parakomórkowa (uszczelnienie – nabłonek jelita, bariera krew-mózg, bariera krew-jądro); polaryzacja komórek nabłonka (oddzielenie domeny apikalnej od bazolateralnej – zapobieganie swobodnej dyfuzji białek i lipidów między domenami). Regulacja przepuszczalności: sygnalizacja Ca2+, kinazy, cytokiny.
- Złącze przylegania (zonula adherens, adherens junction): kadheryny klasyczne (E-kadheryna w nabłonkach, N-kadheryna w neuronach i mięśniach, VE-kadheryna w śródbłonku) – białka transbłonowe, wiązanie homofilne, zależne od Ca2+ (usunięcie Ca2+ → rozpad złącza). Od strony cytoplazmatycznej: kateniny (β-katenina i α-katenina) łączą kadheryny z filamentami aktynowymi – pasmo przylegania (adhesion belt). Znaczenie: utrzymanie integralności tkanek, sygnalizacja (β-katenina jest koaktywatorem transkrypcji w szlaku Wnt – translokacja do jądra → aktywacja genów proliferacji; mutacje APC lub β-kateniny → konstytutywna aktywacja → rak jelita grubego).
- Desmosom (macula adherens): kadheryny desmosomalne (desmogleina 1-4, desmokolina 1-3) wiążą się homofilnie. Od strony cytoplazmatycznej: płytka desmosomalna (plakoglobina, plakofilina, desmoplakina) → zakotwiczenie filamentów pośrednich (keratyna w nabłonkach, desmina w mięśniach). Silne mechanicznie punkty zgrzewania – "nitowanie" komórek nabłonka i mięśnia sercowego. Choroby autoimmunologiczne: pęcherzyca zwykła (pemphigus vulgaris – autoprzeciwciała przeciw desmogleinie 3 → utrata adhezji keratynocytów → pęcherze na skórze i błonach śluzowych).
- Złącze szczelinowe (gap junction, nexus/neksus): półkanał (konekson) = 6 podjednostek koneksyny (Cx, rodzina 21 genów u człowieka; Cx43 – najpowszechniejsza). Dwa koneksony sąsiednich komórek tworzą pełny kanał (średnica poru ~1,5 nm, przepuszczalny dla cząsteczek <1 kDa). Przepływ: jonów (szybkie rozprzestrzenianie potencjału czynnościowego – synapsy elektryczne), metabolitów (glukoza, aminokwasy), wtórnych przekaźników (cAMP, Ca2+, IP3 – koordynacja metaboliczna sąsiednich komórek). Występowanie: mięsień sercowy (szybkie rozchodzenie się pobudzenia), mięśniówka gładka (skurcze synchroniczne – macica podczas porodu), neurony (synapsy elektryczne w siatkówce i korze mózgowej – oscylacje γ), osteocyty (sieć kanalikowa w kościach), hepatocyty (koordynacja metabolizmu wątroby), komórki β wysp Langerhansa (synchronizacja wydzielania insuliny).
- Hemiesmosom: łączy komórkę z błoną podstawną (macierzą zewnątrzkomórkową). Integryna α6β4 wiąże lamininę w błonie podstawnej. Od strony cytoplazmatycznej: plektyna łączy integrynę z filamentami pośrednimi (keratyna). Występowanie: podstawna strona keratynocytów, komórek nabłonka – mocne zakotwiczenie do podłoża.
- Plazmodesmy (rośliny): kanały w ścianie komórkowej wysłane błoną komórkową, przez które przechodzi ER (desmotubula). Łączą protoplasty sąsiednich komórek w symplast. Transport: małe cząsteczki (<1 kDa) dyfundują swobodnie; większe wymagają aktywnego transportu (zmiana rozmiaru poru przez białka motoryczne i cytoszkielet aktynowy). Komunikacja: transport czynników transkrypcyjnych i mRNA między komórkami (np. białko KNOTTED1 w merystemie), rozprzestrzenianie sygnałów obronnych, transport wirusów roślinnych (wirus mozaiki tytoniu TMV).

MACIERZ ZEWNĄTRZKOMÓRKOWA (ECM – Extracellular Matrix) i jej znaczenie w organizmie człowieka:
ECM jest dynamiczną siecią białek i polisacharydów wydzielanych przez komórki (głównie fibroblasty, chondrocyty, osteoblasty). Skład:
- Białka włókniste (strukturalne): kolagen – najobficiej występujące białko u ssaków (25-35% masy białek). Struktura: potrójna helisa (tropokolagen) – sekwencja powtarzalna Gly-X-Y (X często Pro, Y często Hyp – hydroksyprolina, stabilizująca helisę). Hydroksylacja Pro i Lys wymaga witaminy C (kwas askorbinowy) jako kofaktora hydroksylazy prolinowej i lizylowej. Niedobór witaminy C → szkorbut (niedostateczna hydroksylacja → niestabilny kolagen → kruchość naczyń krwionośnych, krwawienie dziąseł, upośledzone gojenie ran). Typy kolagenu: I (90% – skóra, kości, ścięgna, więzadła, zębina), II (chrząstka szklista, ciało szkliste oka – mniej HyPro, więcej glikozylacji), III (tkanka siateczkowata – wątroba, szpik, naczynia krwionośne – włókna retikulinowe), IV (błona podstawna – sieć, nie tworzy włókien), V (włosy, łożysko), VII (fibryle kotwiczące w naskórku – łączy błonę podstawną ze skórą właściwą). Elastyna – sprężystość (rozciąganie i powrót do pierwotnego kształtu), bogata w Gly, Ala, Val, Lys (tworzenie desmozyny i izodesmozyny – mostki sieciujące nadające sprężystość). Włókna elastyczne: rdzeń elastyny otoczony mikrofibrylami fibryliny-1. Mutacje fibryliny-1 → zespół Marfana (wysoki wzrost, długie kończyny, arachnodaktylia – pająkowate palce, wiotkość stawów, tętniak aorty wstępującej – niebezpieczeństwo rozwarstwienia).
- Glikoproteiny adhezyjne: fibronektyna – dimery połączone mostkami S-S na C-końcu, domeny wiążące integryny (sekwencja RGD – Arg-Gly-Asp), kolagen, heparynę. Funkcje: adhezja komórek do ECM, migracja komórek (szlak dla wędrujących fibroblastów podczas gojenia ran i komórek grzebienia nerwowego podczas embriogenezy). Laminina – główne białko błony podstawnej, heterotrimer (łańcuchy α, β, γ), krzyżowe kształty, wiąże integryny i dystroglikan.
- Proteoglikany: rdzeń białkowy + łańcuchy glikozoaminoglikanów (GAG – ujemnie naładowane, silnie hydrofilne). Agrekan – główny proteoglikan chrząstki (setki łańcuchów siarczanu chondroityny i keratanu + kwas hialuronowy → ogromne agregaty o masie >100 MDa → zdolność do odwracalnej kompresji – amortyzacja w stawach). Kwas hialuronowy – jedyny GAG niełączący się z rdzeniem białkowym i niesiarczanowany, syntetyzowany na powierzchni komórki (syntaza HA), główny składnik mazi stawowej, ciała szklistego oka, macierzy mezenchymy podczas rozwoju zarodkowego (umożliwia migrację komórek). Perlekan – proteoglikan błony podstawnej (siarczan heparanu, wiąże czynniki wzrostu FGF).
- Integryny – główne receptory komórkowe dla ECM: heterodimery αβ (18 α + 8 β → 24 kombinacje u człowieka). Wiązanie dwuwartościowych kationów (Ca2+, Mg2+, Mn2+). Dwukierunkowa sygnalizacja: inside-out (sygnały wewnątrzkomórkowe aktywują integrynę → zwiększone powinowactwo do ligandu ECM) i outside-in (wiązanie ECM → klastrowanie integryn → tworzenie zrostów ogniskowych → aktywacja kinaz FAK i Src → sygnały przeżycia, proliferacji, migracji). Zrosty ogniskowe (focal adhesions): kompleksy integryn, białek adaptorowych (talina, winkulina, paksylina), kinaz (FAK) i filamentów aktynowych – miejsca silnej adhezji komórki do podłoża, "czujniki" mechaniczne (mechanotransdukcja – komórka wyczuwa sztywność podłoża i odpowiednio zmienia swój cytoszkielet i ekspresję genów).
"""

BIOLOGY_EXTRA_METABOLIZM = r"""

ROZSZERZENIE – SZCZEGÓŁOWE SZLAKI METABOLICZNE I REGULACJA:

GLIKOLIZA – SZCZEGÓŁOWY OPIS 10 ETAPÓW (cytozol):
Faza inwestycji energii (1-5, zużycie 2 ATP):
1. Glukoza + ATP → glukozo-6-fosforan + ADP (heksokinaza/glukokinaza). Heksokinaza (wszystkie tkanki, Km ~0,1 mM – wysoka afiniczność, hamowana przez G-6-P); glukokinaza (wątroba, trzustka, Km ~10 mM – niska afiniczność, aktywowana glukozą po posiłku, nie hamowana przez G-6-P). Nieodwracalna.
2. Glukozo-6-fosforan ⇌ fruktozo-6-fosforan (izomeraza fosfoglukozowa).
3. Fruktozo-6-fosforan + ATP → fruktozo-1,6-bisfosforan + ADP (fosfofruktokinaza-1, PFK-1). GŁÓWNY PUNKT REGULACJI GLIKOLIZY. Hamowana allosterycznie przez ATP i cytrynian (sygnały wysokiego stanu energetycznego). Aktywowana przez AMP i fruktozo-2,6-bisfosforan (sygnał niskiego stanu energetycznego). Nieodwracalna.
4. Fruktozo-1,6-bisfosforan ⇌ fosfodihydroksyaceton (DHAP) + aldehyd 3-fosfoglicerynowy (G3P) (aldolaza).
5. DHAP ⇌ G3P (izomeraza triozofosforanowa). Tylko G3P wchodzi w dalszy szlak → 2 cząsteczki G3P z 1 glukozy.

Faza zwrotu energii (6-10, produkcja 4 ATP + 2 NADH):
6. G3P + NAD⁺ + Pi ⇌ 1,3-bisfosfoglicerynian (1,3-BPG) + NADH + H⁺ (dehydrogenaza 3-fosfoglicerynianowa). Utlenienie aldehydu do kwasu + przyłączenie fosforanu → wysokoenergetyczne wiązanie acylowo-fosforanowe.
7. 1,3-BPG + ADP ⇌ 3-fosfoglicerynian (3-PG) + ATP (kinaza fosfoglicerynianowa). PIERWSZA FOSFORYLACJA SUBSTRATOWA. Bilans: 0 (zużyto 2 ATP w fazie 1, odzyskano 2 ATP – po 1 na każdą cząsteczkę G3P).
8. 3-PG ⇌ 2-fosfoglicerynian (mutaza fosfoglicerynianowa).
9. 2-PG ⇌ fosfoenolopirogronian (PEP) + H2O (enolaza). Dehydratacja → wysokoenergetyczne wiązanie enolowo-fosforanowe. Hamowana przez fluorek (kompleks z Mg²⁺ i fosforanem – stosowany jako inhibitor glikolizy przy pobieraniu krwi na oznaczenie glukozy).
10. PEP + ADP → pirogronian + ATP (kinaza pirogronianowa). DRUGA FOSFORYLACJA SUBSTRATOWA. Produkcja 2 ATP (po 1 na każdy PEP). Nieodwracalna. Aktywowana przez fruktozo-1,6-bisfosforan (sprzężenie zwrotne do przodu – feedforward), hamowana przez ATP, alaninę, glukagon (przez fosforylację PKA).

Bilans glikolizy na 1 glukozę: Glukoza + 2NAD⁺ + 2ADP + 2Pi → 2 pirogronian + 2NADH+H⁺ + 2ATP + 2H2O. Bilans netto: +2 ATP (substratowa fosforylacja).

Losy pirogronianu w zależności od dostępności tlenu:
- Warunki tlenowe: pirogronian wchodzi do mitochondrium → dekarboksylacja oksydacyjna → acetylo-CoA → cykl Krebsa → łańcuch oddechowy (łącznie ~30-32 ATP z 1 glukozy).
- Warunki beztlenowe (intensywny wysiłek, niedotlenienie): fermentacja mleczanowa: pirogronian + NADH + H⁺ → mleczan + NAD⁺ (dehydrogenaza mleczanowa LDH). Regeneracja NAD⁺ umożliwia kontynuację glikolizy.
- Drożdże (beztlenowo): fermentacja alkoholowa: pirogronian → aldehyd octowy + CO2 → etanol + NAD⁺.

CYKL KREBSA – SZCZEGÓŁOWY OPIS 8 ETAPÓW (macierz mitochondrialna):
1. Acetylo-CoA (2C) + szczawiooctan (4C) + H2O → cytrynian (6C) + CoA-SH (syntaza cytrynianowa). Nieodwracalna, regulowana (hamowana przez ATP, NADH, bursztynylo-CoA).
2. Cytrynian ⇌ izocytrynian (akonitaza). Przez pośredni cis-akonitan.
3. Izocytrynian + NAD⁺ → α-ketoglutaran (5C) + CO2 + NADH + H⁺ (dehydrogenaza izocytrynianowa). Aktywowana przez ADP i Ca²⁺, hamowana przez ATP i NADH. PIERWSZA DEKARBOKSYLACJA.
4. α-ketoglutaran + NAD⁺ + CoA-SH → bursztynylo-CoA (4C) + CO2 + NADH + H⁺ (dehydrogenaza α-ketoglutaranowa). Kompleks wieloenzymatyczny podobny do dehydrogenazy pirogronianowej. Nieodwracalna. DRUGA DEKARBOKSYLACJA.
5. Bursztynylo-CoA + GDP + Pi ⇌ bursztynian (4C) + CoA-SH + GTP (syntetaza bursztynylo-CoA, inaczej tiokinaza bursztynianowa). JEDYNA FOSFORYLACJA SUBSTRATOWA W CYKLU KREBSA. GTP + ADP ⇌ ATP + GDP (kinaza difosfonukleozydowa).
6. Bursztynian + FAD → fumaran + FADH2 (dehydrogenaza bursztynianowa). Enzym związany z wewnętrzną błoną mitochondrialną – JEDYNY enzym cyklu Krebsa, który jest integralnym białkiem błonowym (wszystkie pozostałe są rozpuszczalne w macierzy). Jest to jednocześnie Kompleks II łańcucha oddechowego. Hamowana przez malonian (inhibicja kompetycyjna – klasyczny przykład biochemiczny!).
7. Fumaran + H2O ⇌ L-jabłczan (fumaraza). Hydratacja wiązania podwójnego.
8. L-jabłczan + NAD⁺ ⇌ szczawiooctan (4C) + NADH + H⁺ (dehydrogenaza jabłczanowa). Regeneracja akceptora dla acetylo-CoA. Silnie endergoniczna w warunkach standardowych (ΔG°' ≈ +30 kJ/mol), ale w komórce sprzężona z szybkim zużyciem szczawiooctanu (syntaza cytrynianowa) → przesunięcie równowagi (ΔG ≈ 0).

Bilans 1 obrotu cyklu Krebsa: Acetylo-CoA + 3NAD⁺ + FAD + GDP + Pi + 2H2O → 2CO2 + 3NADH+H⁺ + FADH2 + GTP + CoA-SH.
Na 1 glukozę (2 pirogroniany → 2 acetylo-CoA): 2 obroty cyklu → 6NADH + 2FADH2 + 2GTP + 4CO2. Poza cyklem Krebsa: 2NADH z glikolizy + 2NADH z dekarboksylacji pirogronianu = 10NADH + 2FADH2 + 2GTP (→ 2ATP) + 2ATP z glikolizy.

ŁAŃCUCH ODDECHOWY – SZCZEGÓŁOWA STRUKTURA KOMPLEKSÓW:
Kompleks I (NADH:ubichinon oksydoreduktaza, NADH dehydrogenaza): 45 podjednostek (14 rdzeniowych, homologicznych z enzymem bakteryjnym; 31 pomocniczych), masa ~1 MDa, jeden z największych kompleksów błonowych. Grupa prostetyczna: mononukleotyd flawinowy (FMN) + 8 centrów Fe-S (2 centra [2Fe-2S] + 6 centrów [4Fe-4S]). Mechanizm: NADH → FMN → centra Fe-S → ubichinon (Q). Sprzężone z translokacją 4 H⁺ z macierzy do przestrzeni międzybłonowej (mechanizm sprzężenia – prawdopodobnie przez zmiany konformacyjne, nie bezpośrednio przez pompowanie). Inhibitory: rotenon (środek owadobójczy i środek do ogłuszania ryb), amytal (barbituran), piericydyna A (antybiotyk).
Kompleks II (dehydrogenaza bursztynianowa): 4 podjednostki (SDHA – katalityczna, FAD, wiąże bursztynian; SDHB – 3 centra Fe-S; SDHC i D – transbłonowe, wiążą hem b i ubichinon). Jedyny enzym cyklu Krebsa związany z błoną. Nie pompuje H⁺ (mniej energii z FADH2 niż z NADH). Substrat: FADH2 (z utlenienia bursztynianu). Produkt: QH2 (ubichinol). Inhibitor: malonian (analog bursztynianu, kompetycyjny).
Kompleks III (cytochrom bc1, ubichinol:cytochrom c oksydoreduktaza): dimer (11 podjednostek każdy monomer). Grupy prostetyczne: hem bL, hem bH, hem c1, centrum [2Fe-2S] (Rieskego). Cykl Q (mechanizm sprzężenia translokacji protonów z transportem elektronów): QH2 + 2 cyt c(ox) + 2H⁺N → Q + 2 cyt c(red) + 4H⁺P (indeks N – strona ujemna/macierz; P – strona dodatnia/przestrzeń międzybłonowa). Na każde 2 e⁻ przepływające z QH2 na cytochrom c translokowane są 4 H⁺. Inhibitory: antymycyna A, myksotiazol, strobiluryny (fungicydy pochodzące od grzybów).
Cytochrom c – małe (12 kDa) białko peryferyjne na zewnętrznej stronie wewnętrznej błony, przenosi pojedynczy elektron (hem c, kowalencyjnie związany z białkiem przez wiązania tioestrowe do Cys), ruchliwy nośnik między Kompleksem III i IV.
Kompleks IV (cytochrom c oksydaza, COX): 13 podjednostek (3 mtDNA + 10 jądrowe). 4 centra redoks: CuA (dwa jony Cu), hem a, hem a3, CuB. Akceptor końcowy: O2 + 4e⁻ + 4H⁺ → 2H2O. Mechanizm redukcji O2 do H2O zapobiega powstawaniu reaktywnych form tlenu (częściowo zredukowany tlen – rodnik ponadtlenkowy O2•⁻). Na każde 4 e⁻ przepływające: 4 H⁺ zużywane na utworzenie 2 H2O (z macierzy) + 4 H⁺ przepompowane (z macierzy do przestrzeni międzybłonowej). Inhibitory: cyjanek CN⁻ (wiąże się z hem a3, blokuje transfer e⁻ na O2 → śmierć przez uduszenie na poziomie komórkowym!), azydek N3⁻, tlenek węgla CO (konkuruje z O2).

Syntaza ATP (Kompleks V, F-ATPaza, F0F1-ATPaza):
F0 (sektor transbłonowy, kanał protonowy): podjednostki a, b2, c10-14 (u człowieka c8, pierścień c – rotuje!). Przepływ H⁺ przez kanał między a i pierścieniem c napędza rotację pierścienia c. F1 (sektor katalityczny, w macierzy): podjednostki α3β3γδε. β – miejsca katalityczne syntezy ATP. γ – centralny wał, rotuje wraz z pierścieniem c, powoduje cykliczne zmiany konformacji podjednostek β (mechanizm zmiany wiązania – binding change mechanism, Paul Boyer, Nagroda Nobla 1997). Trzy stany konformacyjne β: O (open – uwalnianie ATP), L (loose – wiązanie ADP + Pi), T (tight – synteza ATP). Każdy obrót γ o 120° zmienia konformację wszystkich 3 podjednostek β.
Stechiometria: Translokacja ~8-14 H⁺ na 1 pełny obrót (zależnie od liczby c w pierścieniu). Jeden obrót → 3 ATP (po jednym na każdą podjednostkę β). Czyli ~2,7-4 H⁺ na 1 ATP. Dodatkowo 1 H⁺ zużywany na transport Pi do macierzy (symporter fosforanowy) i ~1 H⁺ na wymianę ATP4⁻ (w macierzy) na ADP3⁻ (w cytozolu) przez translokazę ATP/ADP (ANT – Adenine Nucleotide Translocase).
Bilans całkowity oddychania komórkowego: C6H12O6 + 6O2 + ~30-32ADP + ~30-32Pi → 6CO2 + 6H2O + ~30-32ATP. Teoretyczne maksimum ~36-38; rzeczywista wydajność ~30-32 (część energii gradientu protonowego rozpraszana jest jako ciepło, szczególnie w tkance tłuszczowej brunatnej – termogenina UCP1).

FOTOSYNTEZA – MECHANIZM MOLEKULARNY:
Fotosystem II (PSII, centrum reakcji P680 – dimer chlorofilu a absorbujący przy 680 nm): Światło → energia przekazywana z antenowych cząsteczek chlorofilu (kompleks LHCII) do P680 → P680* (wzbudzony, silny reduktor) → przekazanie e⁻ na feofitynę (Pheo, bezmagnezowy chlorofil) w czasie ~3 ps → następnie na plastochinon QA (związany, jednoelektronowy akceptor) → QB (ruchliwy, dwuelektronowy akceptor, po przyjęciu 2e⁻ i 2H⁺ tworzy PQH2 – plastochinol). PQH2 dyfunduje w błonie do kompleksu cytochromów b6f.
Fotoliza H2O (kompleks rozkładający wodę, OEC – Oxygen Evolving Complex): klaster Mn4CaO5 w sercu PSII. 2H2O → O2 + 4H⁺ + 4e⁻. Cykl Koksa (5 stanów S0 → S1 → S2 → S3 → S4 → S0, wg liczby utlenionych jonów Mn). Na każde 4 zaabsorbowane fotony → 1 O2, 4H⁺ do światła tylakoidu.
Kompleks cytochromów b6f (analog Kompleksu III łańcucha oddechowego): utlenia PQH2, przekazuje e⁻ na plastocyjaninę (PC, małe białko zawierające Cu). Cykl Q – translokacja H⁺ ze stromy do światła tylakoidu → gradient protonowy (ΔpH, światło tylakoidu zakwasza się do pH ~5, stroma pozostaje ~pH 8).
Fotosystem I (PSI, P700): absorbuje dłuższe fale (700 nm). Wzbudzony P700* przekazuje e⁻ na akceptor A0 (chlorofil) → filochinon (A1) → centra Fe-S (Fx, FA, FB) → ferredoksyna (Fd, białko Fe-S na powierzchni stromy). Reduktaza ferredoksyna-NADP⁺ (FNR, flawoproteina): 2Fd(red) + NADP⁺ + H⁺ → 2Fd(ox) + NADPH.
Fotofosforylacja niecykliczna (główny szlak): PSII → PQ → b6f → PC → PSI → Fd → NADP⁺. Produkty: ATP (z gradientu H⁺), NADPH (z redukcji NADP⁺), O2 (z fotolizy H2O). Potrzebne oba fotosystemy.
Fotofosforylacja cykliczna (tylko wokół PSI): PSI → Fd → PQ → b6f → PC → PSI. Produkt: TYLKO ATP (bez NADPH i O2). Występuje, gdy komórka potrzebuje więcej ATP niż NADPH (np. do cyklu Calvina, gdzie stosunek ATP:NADPH = 3:2).

CYKL CALVINA-BENSONA-BASSHAMA – FAZA CIEMNA (stroma):
1. Karboksylacja: RuBP (rybulozo-1,5-bisfosforan, 5C) + CO2 + H2O → 2 × 3-PGA (3-fosfoglicerynian, 3C). Katalizowana przez RuBisCO (rybulozo-1,5-bisfosforan karboksylaza/oksygenaza) – najobficiej występujące białko na Ziemi (~30-50% białek rozpuszczalnych liścia). Powolny enzym (kcat ~3 s⁻¹ vs ~10⁶ s⁻¹ dla anhydrazy węglanowej) → konieczność ogromnych ilości. Podwójna aktywność: karboksylaza (CO2 + RuBP → 2 × 3-PGA – użyteczna dla fotosyntezy) i oksygenaza (O2 + RuBP → 3-PGA + fosfoglikolan – fotooddychanie, strata węgla i energii). Przy wysokim CO2 i niskim O2 dominuje karboksylacja.
2. Redukcja: 3-PGA + ATP → 1,3-BPG (kinaza fosfoglicerynianowa); 1,3-BPG + NADPH + H⁺ → G3P (aldehyd-3-fosfoglicerynowy) + NADP⁺ + Pi (dehydrogenaza 3-fosfoglicerynianowa – odwrotność reakcji 6 glikolizy!). Na 6 cząsteczek 3-PGA: potrzeba 6 ATP + 6 NADPH → 6 G3P.
3. Regeneracja: 5 z 6 cząsteczek G3P przechodzi szereg reakcji (transketolaza, transaldolaza, izomerazy, epimerazy, kinazy) → 3 RuBP + 3 Pi. Potrzeba 3 ATP. Jedna cząsteczka G3P (3C) opuszcza cykl → 2 G3P → glukoza (6C).
Sumarycznie na 1 cząsteczkę glukozy: 6CO2 + 18ATP + 12NADPH + 12H⁺ + 12H2O → C6H12O6 + 18ADP + 18Pi + 12NADP⁺.

FOTOSYNTEZA C4 (mechanizm koncentracji CO2, adaptacja do gorącego i suchego klimatu):
Rośliny C4 (kukurydza, trzcina cukrowa, sorgo, proso, ~3% gatunków roślin, ale ~25% globalnej produktywności ekosystemów). Anatomia Kranza: dwie warstwy komórek wokół wiązek przewodzących – mezofil (zewnętrzna) i komórki pochew okołowiązkowych (wewnętrzna, grubościenne, z chloroplastami). Mechanizm:
1. W mezofilu: CO2 + HCO3⁻ + PEP (fosfoenolopirogronian) → szczawiooctan (C4, 4 węgle) + Pi. Enzym: karboksylaza PEP (PEPC, PEP carboxylase) – wysoka afiniczność do HCO3⁻, nie ma aktywności oksygenazowej (w przeciwieństwie do RuBisCO).
2. Szczawiooctan → jabłczan (C4) lub asparaginian (w zależności od podtypu C4).
3. Transport do komórek pochew → dekarboksylacja → CO2 + pirogronian (C3).
4. CO2 wchodzi do cyklu Calvina (RuBisCO tylko w chloroplastach komórek pochew!).
5. Pirogronian wraca do mezofilu, zużywa 2 ATP (przez dikinazę fosforanową pirogronianu) → PEP.
Koszt energetyczny: 5 ATP / 2 NADPH na 1 zasymilowane CO2 (vs 3 ATP / 2 NADPH w C3). Ale zysk: minimalizacja fotooddychania (wysokie [CO2] w komórkach pochew), wyższa wydajność w wysokich temperaturach (>30°C) i przy intensywnym świetle.

FOTOSYNTEZA CAM (Crassulacean Acid Metabolism, gruboszowate, sukulenty):
Adaptacja do klimatu pustynnego (kaktusy, agawy, ananasy, grubosze, storczyki, ~6% gatunków). Szparki otwarte w nocy (mniejsza transpiracja) → CO2 wiązane przez PEPC → jabłczan magazynowany w wakuoli (zakwaszenie soku komórkowego). W dzień szparki zamknięte (oszczędność H2O) → jabłczan z wakuoli → dekarboksylacja → CO2 do cyklu Calvina. Rozdzielenie czasowe (nie przestrzenne jak w C4). Niższa wydajność fotosyntezy, ale ekstremalna oszczędność wody (stosunek transpiracji do asymilacji: C3 ~500 g H2O/g CO2, C4 ~250, CAM ~50-100!).

REGULACJA METABOLIZMU:
- Allosteryczna: enzymy kluczowych szlaków metabolicznych mają miejsca allosteryczne dla efektorów (aktywatorów i inhibitorów). Np. PFK-1 (glikoliza) – hamowana przez ATP (dużo energii → spowolnienie glikolizy), aktywowana przez AMP (mało energii → przyspieszenie glikolizy); fruktozo-1,6-bisfosfataza (glukoneogeneza) – odwrotnie. Cykl substratowy (futile cycle): PFK-1 vs FBPaza-1 – jednoczesne działanie obu = hydroliza ATP bez efektu metabolicznego → produkcja ciepła (używane przez trzmiele do ogrzania mięśni przed lotem).
- Kowalencyjna (fosforylacja/defosforylacja): kinazy białkowe vs fosfatazy białkowe. Glikogenoliza: glukagon/adrenalina → cAMP → PKA → fosforylacja fosforylazy b (nieaktywnej) → fosforylaza a (aktywna) → rozkład glikogenu do glukozo-1-fosforanu; jednocześnie fosforylacja syntazy glikogenowej (inaktywacja) → zatrzymanie syntezy glikogenu. Kaskada amplifikacji: 10⁻¹⁰ M glukagonu → 10⁻⁶ M cAMP → 10⁻³ M glukozy we krwi.
- Hormonalna: insulina (po posiłku) – aktywacja fosfodiesterazy (→ cAMP↓), aktywacja fosfataz białkowych (defosforylacja → synteza glikogenu, glikoliza, synteza kwasów tłuszczowych). Glukagon i adrenalina (głodzenie, stres) – aktywacja cyklazy adenylanowej (→ cAMP↑), aktywacja PKA → fosforylacja → glikogenoliza, glukoneogeneza, lipoliza.
- Na poziomie ekspresji genów: długoterminowa adaptacja metaboliczna (np. głodzenie → wzrost ekspresji enzymów glukoneogenezy; dieta wysokowęglowodanowa → wzrost ekspresji enzymów lipogenezy). Czynniki transkrypcyjne: SREBP (lipogeneza), CREB (glukoneogeneza), FOXO (głodzenie), PPARγ (adipogeneza, wrażliwość insulinowa – cel tiazolidynedionów)."""

BIOLOGY_EXTRA_GENETYKA = r"""

ROZSZERZENIE – GENETYKA MOLEKULARNA I REGULACJA EKSPRESJI GENÓW:

REPLIKACJA DNA – MECHANIZM MOLEKULARNY U EUKARIOTÓW:
Inicjacja: kompleks ORC (Origin Recognition Complex) rozpoznaje sekwencje ARS (Autonomously Replicating Sequences) → rekrutacja białek Cdc6 i Cdt1 → załadowanie helikazy MCM2-7 (kompleks licencyjny, nieaktywny w G1). W fazie S: kinazy CDK i DDK fosforylują MCM → aktywacja helikazy + rekrutacja polimeraz. Ścisła kontrola: licencja na replikację wydawana jest tylko raz na cykl komórkowy (zapobieganie rereplikacji → stabilność genomu).
Wydłużanie: Widełki replikacyjne poruszają się z prędkością ~50 nt/s (eukariota) vs ~1000 nt/s (bakterie E. coli). Eukariota kompensują wolniejszą polimerazę przez większą liczbę miejsc inicjacji replikacji (dziesiątki tysięcy).
Polimerazy DNA u eukariotów:
- Pol α (alfa): kompleks z prymazą – synteza startera RNA + krótki fragment DNA (~20-30 nt).
- Pol δ (delta): główna polimeraza nici opóźnionej, synteza fragmentów Okazaki (100-200 nt). Posiada aktywność 3'→5' egzonukleazy (korekta).
- Pol ε (epsilon): główna polimeraza nici wiodącej, wysoka procesywność (>100 kb bez odłączania, dzięki białku PCNA – clamp).
- Pol γ (gamma): replikacja mitochondrialnego DNA.
- Pol β, κ, η, ι, ζ: naprawcze i specjalne (polimeraza η omija dimery tyminowe – mutacja → Xeroderma pigmentosum wariantowa).
Białka pomocnicze: PCNA (Proliferating Cell Nuclear Antigen) – homotrimeryczny pierścień ("clamp") otaczający DNA, zwiększa procesywność polimeraz δ i ε. RFC (Replication Factor C) – ładuje PCNA na DNA (clamp loader). RPA (Replication Protein A) – eukariotyczny odpowiednik SSB, wiąże jednoniciowe DNA, chroni przed nukleazami.
Problem replikacji końców chromosomów (telomerów): nić opóźniona nie może być w pełni zreplikowana na samym końcu (brak miejsca dla ostatniego startera RNA) → telomery skracają się z każdym podziałem (limit Hayflicka, ~50-70 podziałów dla ludzkich fibroblastów). Telomeraza – odwrotna transkryptaza z własnym matrycowym RNA (TERC – Telomerase RNA Component), wydłuża telomery przez dodawanie powtórzeń TTAGGG. Aktywna w komórkach macierzystych, linii płciowej, limfocytach i >85% komórek nowotworowych (umożliwia nieograniczone podziały → cel terapii przeciwnowotworowych). W komórkach somatycznych telomeraza nieaktywna → starzenie replikacyjne.

TRANSKRYPCJA U EUKARIOTÓW – SZCZEGÓŁOWE MECHANIZMY REGULACJI:
Polimerazy RNA u eukariotów:
- Pol I: transkrypcja genów rRNA 18S, 5,8S, 28S (w jąderku, ~50% całkowitej transkrypcji).
- Pol II: transkrypcja genów kodujących białka (mRNA) i większości niekodujących RNA (snRNA, miRNA, lncRNA). ~30%. Kluczowa dla ekspresji genów – tematem regulacji.
- Pol III: transkrypcja tRNA, 5S rRNA, małych RNA jądrowych (U6 snRNA). ~20%.

Inicjacja transkrypcji Pol II – kompleks preinicjacyjny (PIC):
Promotor rdzeniowy: TATA box (TATAAA, pozycja -25, rozpoznawana przez TBP – TATA-Binding Protein), Inr (Initiator), DPE (Downstream Promoter Element), BRE (TFIIB Recognition Element).
Kolejność składania PIC:
1. TFIID (kompleks TBP + ~14 TAFs – TBP-Associated Factors) rozpoznaje i wiąże promotor.
2. TFIIB – stabilizuje kompleks, określa kierunek transkrypcji.
3. Kompleks Pol II + TFIIF – rekrutacja polimerazy do promotora.
4. TFIIE – rekrutacja i regulacja TFIIH.
5. TFIIH – helikaza (podjednostki XPB i XPD, otwiera podwójną helisę – tworzenie bańki transkrypcyjnej ~10-15 nt) + kinaza (podjednostka CDK7, fosforylacja C-końcowej domeny CTD Pol II w Ser5 → uwolnienie Pol II z promotora – start elongacji).
Białka aktywatorowe (czynniki transkrypcyjne): wiążą się ze specyficznymi sekwencjami DNA (enhancery, silencery, elementy odpowiedzi – oddalone nawet o dziesiątki tysięcy pz od promotora!). Domena aktywacji (oddziałuje z kompleksem mediator lub bezpośrednio z TFIID/TFIIB). Mediator – ogromny kompleks białkowy (~30 podjednostek, masa ~1,5 MDa), pośredniczy między aktywatorami a aparatem transkrypcyjnym (Pol II + ogólne czynniki transkrypcyjne), integruje sygnały od wielu aktywatorów i represorów.
Regulacja chromatyny: Kompleksy remodelujące chromatynę (SWI/SNF, ISWI, NuRD, CHD) – zależne od ATP, przesuwają nukleosomy, odsłaniając lub zasłaniając promotory. Acetylacja histonów (HAT – Histone Acetyltransferases: p300/CBP, GCN5/PCAF; acetylacja lizyn w N-końcowych ogonach histonów H3 i H4 → neutralizacja dodatniego ładunku lizyny → osłabienie oddziaływania histon-DNA → rozluźnienie chromatyny → aktywacja transkrypcji). Deacetylacja (HDAC – Histone Deacetylases: usunięcie grup acetylowych → kondensacja chromatyny → represja transkrypcji). Metylacja histonów: H3K4me3 (trimetylacja lizyny 4 histonu H3) – marker aktywnej transkrypcji (w promotorach); H3K27me3 – marker represji (kompleks Polycomb PRC2 – metylacja, PRC1 – ubikwitynacja H2A → kondensacja); H3K9me3 – heterochromatyna (wiąże białko HP1 – Heterochromatin Protein 1). Fosforylacja histonu H2AX (γH2AX) – marker dwuniciowych pęknięć DNA (naprawa).
Kod histonowy: kombinacja różnych modyfikacji chemicznych na ogonach histonów jest "odczytywana" przez białka z domenami rozpoznającymi modyfikacje (bromodomena – acetylacja; chromodomena – metylacja; PHD finger – metylacja). Integracja sygnałów aktywujących i represyjnych → decyzja o poziomie transkrypcji.

Obróbka potranskrypcyjna mRNA u eukariotów (wszystkie etapy w jądrze, sprzężone z transkrypcją przez CTD Pol II):
1. Capping (czapeczka 5'): 7-metyloguanozyna (m⁷G) przyłączona przez mostek 5'-5' trifosforanowy do pierwszego nukleotydu RNA. Funkcje: ochrona 5' przed egzonukleazami 5'→3', rozpoznanie przez kompleks wiążący czapeczkę (CBC, później eIF4E) – niezbędne do inicjacji translacji, splicing pierwszego intronu, eksport z jądra.
2. Splicing (wycinanie intronów): spliceosom – ogromny rybonukleoproteinowy kompleks (snRNP: U1, U2, U4, U5, U6 + >100 białek). Sekwencje konsensusowe na granicach intronów: GU (5' splice site, donor), AG (3' splice site, akceptor), sekwencja rozgałęzienia (branch point, A, ~20-50 nt przed 3' końcem), trakt polipirymidynowy. Mechanizm dwuetapowy: (1) atak 2'-OH adenozyny w branch point na 5' koniec intronu → wiązanie 2'-5' fosfodiestrowe → struktura lariatu; (2) atak uwolnionego 3'-OH eksonu na 3' splice site → połączenie eksonów + uwolnienie intronu w formie lariatu. Splicing alternatywny: jeden gen → wiele różnych mRNA i białek (izoform). Np. gen DSCAM u Drosophila: >38 000 różnych izoform (więcej niż genów w całym genomie muszki!); u człowieka gen tropomiozyny, gen α-tropomiozyny (kalcytonina/CGRP), gen Bcl-x (Bcl-xL antyapoptotyczny / Bcl-xS proapoptotyczny przez alternatywne 5' splice site). Regulacja splicingu: białka SR (serine/arginine-rich – aktywatory, wiążą sekwencje wzmacniające splicing ESE) i białka hnRNP (heterogeneous nuclear RNP – represory, wiążą sekwencje wyciszające splicing ESS/ISS).
3. Poliadenylacja (ogon poli-A): endonukleaza CPSF rozpoznaje sygnał poliadenylacji AAUAAA → cięcie RNA ~10-35 nt za sygnałem → polimeraza poli-A (PAP) dodaje ~200 reszt adenozyny (bez matrycy!). Ogon poli-A: stabilizacja mRNA (chroni przed egzonukleazami 3'→5'), eksport z jądra (białko PABP – PolyA Binding Protein), inicjacja translacji (PABP oddziałuje z eIF4G → pseudokolista struktura mRNA). Deadenylacja (skracanie ogona poli-A) jest pierwszym i często limitującym etapem degradacji mRNA (szlak Deadenylation-Dependent Decapping → 5'→3' egzonukleaza Xrn1).

Regulacja ekspresji genów – dodatkowe poziomy:
- Transkrypcyjny: czynniki transkrypcyjne, remodelacja chromatyny, modyfikacje histonów, metylacja DNA (CpG islands – wyspy CpG w promotorach; metylacja CpG przez DNMT → wiązanie białek MeCP2 → rekrutacja HDAC → represja; metylacja DNA jest dziedziczona epigenetycznie – imprinting genomowy, inaktywacja chromosomu X).
- Potranskrypcyjny: splicing alternatywny, edycja RNA (deaminaza adenozynowa ADAR – A→I w mRNA; deaminaza cytozynowa APOBEC – C→U w mRNA apolipoproteiny B → przedwczesny kodon stop → krótsze białko ApoB48 w jelicie vs ApoB100 w wątrobie), transport z jądra, degradacja mRNA, interferencja RNA (miRNA, siRNA).
- Translacyjny: fosforylacja czynników inicjacji translacji (eIF2α – hamowanie translacji przy stresie, niedoborze aminokwasów; kinaza mTOR – globalna kontrola syntezy białek w odpowiedzi na dostępność składników odżywczych i czynniki wzrostu).
- Posttranslacyjny: fałdowanie białek (chaperony – Hsp70, Hsp60/chaperonina, Hsp90), modyfikacje kowalencyjne (fosforylacja, acetylacja, metylacja, ubikwitynacja – degradacja w proteasomie 26S), lokalizacja wewnątrzkomórkowa (sekwencje sygnałowe kierują białka do odpowiednich przedziałów), degradacja (proteasom – ubikwityna; lizosomy – autofagia; kaspazy – apoptoza).
- Epigenetyka: zmiany dziedziczne w ekspresji genów niezwiązane ze zmianą sekwencji DNA. Mechanizmy: metylacja DNA (wyspy CpG, DNMT1 – metylacja podtrzymująca podczas replikacji, DNMT3a/b – metylacja de novo), modyfikacje histonów (acetylacja, metylacja, fosforylacja, ubikwitynacja), remodelacja chromatyny, niekodujące RNA (lncRNA XIST – inaktywacja chromosomu X; HOTAIR – regulacja genów HOX). Przykłady epigenetyki: imprinting genomowy (matczyny lub ojcowski allel genu jest wyciszany przez metylację – np. gen IGF2 tylko z allelu ojcowskiego, gen H19 tylko z matczynego; zaburzenia → zespół Pradera-Williego, zespół Angelmana), inaktywacja chromosomu X u samic ssaków (losowa, zachodzi wczesnym rozwoju zarodkowym; ciałko Barra – skondensowany nieaktywny X; gen XIST – transkrypcja lncRNA XIST tylko z nieaktywnego X, XIST "maluje" chromosom i rekrutuje kompleksy represorowe Polycomb), różnicowanie komórek (wszystkie komórki organizmu mają identyczne DNA, ale różnią się wzorem ekspresji genów – epigenomem; przeprogramowanie epigenetyczne w komórkach iPS – indukowanych pluripotencjalnych komórkach macierzystych, Nagroda Nobla 2012, Yamanaka: czynniki transkrypcyjne Oct4, Sox2, Klf4, c-Myc).

MUTACJE I ICH SKUTKI FUNKCJONALNE:
- Mutacje punktowe (zmiana pojedynczego nukleotydu): Tranzycja (puryna → puryna: A↔G; pirymidyna → pirymidyna: C↔T) vs transwersja (puryna ↔ pirymidyna). Częściej obserwuje się tranzycje (mniejsze zaburzenie struktury DNA).
- Podstawienia w regionie kodującym: Synonimiczne (ciche, silent) – zmiana kodonu, ale ten sam aminokwas (degeneracja kodu, głównie 3. nukleotyd). Niesynonimiczne: missensowne – zmiana aminokwasu (np. anemia sierpowata: GAG→GTG, Glu→Val w 6. pozycji łańcucha β hemoglobiny – HbS, zmiana hydrofilowej reszty na hydrofobową → polimeryzacja deoksy-HbS → sierpowate erytrocyty). Nonsensowne – kodon stop (TAA, TAG, TGA) zamiast aminokwasu → przedwczesna terminacja → skrócone białko, zwykle nieaktywne (np. mutacje nonsensowne w genie dystrofiny → dystrofia mięśniowa Duchenne'a).
- Insercje/delecje (indele): jeśli nie są wielokrotnością 3 → przesunięcie ramki odczytu (frameshift) → całkowicie zmieniona sekwencja aminokwasów za miejscem mutacji + przedwczesny kodon stop → najczęściej całkowita utrata funkcji białka.
- Mutacje w regionach regulatorowych (promotor, enhancer, splice sites): zmiana poziomu lub wzorca ekspresji genu (np. mutacja w promotorze genu laktazy → utrzymanie ekspresji laktazy w życiu dorosłym – tolerancja laktozy, częsta w populacjach europejskich).
- Mutacje dynamiczne (ekspansja powtórzeń trójnukleotydowych): zwiększenie liczby powtórzeń ponad wartość progową → choroba. Np. choroba Huntingtona (CAG w eksonie 1 genu HTT, ≥40 powtórzeń → poliglutaminowe agregaty białka huntingtyny → neurodegeneracja prążkowia; im więcej powtórzeń, tym wcześniejszy początek choroby – zjawisko antycypacji), zespół łamliwego chromosomu X (Fragile X, CGG w 5'UTR genu FMR1, >200 powtórzeń → metylacja i wyciszenie genu → niepełnosprawność intelektualna).

Systemy naprawcze DNA (ochrona integralności genomu):
1. Naprawa bezpośrednia (Direct Reversal): fotoliaza (enzym naprawiający dimery tyminowe przy użyciu energii światła – fotoreaktywacja, obecna u bakterii, grzybów, roślin, NIE u ssaków łożyskowych!); MGMT (O⁶-metyloguaninowa metylotransferaza DNA – usuwa grupy alkilowe z guaniny, "samobójczy" enzym – przenosi grupę metylową na własną cysteinę i jest degradowany).
2. Naprawa przez wycinanie zasady (BER – Base Excision Repair): glikozylazy DNA rozpoznają i usuwają uszkodzoną/nieprawidłową zasadę (np. uracyl w DNA – glikozylaza uracylowa; 8-oksoguanina – OGG1; hipoksantyna) → miejsce AP (apurynowe/apirymidynowe) → endonukleaza APE1 tnie szkielet → Pol β wypełnia lukę → ligaza łączy.
3. Naprawa przez wycinanie nukleotydu (NER – Nucleotide Excision Repair): usuwa duże, zniekształcające helisę uszkodzenia (dimery tyminowe UV, addukty chemiczne – benzopiren z dymu tytoniowego). Dwie podścieżki: GG-NER (Global Genomic – rozpoznanie przez kompleks XPC-HR23B, wykrywanie zniekształcenia helisy) i TC-NER (Transcription-Coupled – polimeraza RNA zatrzymuje się na uszkodzeniu, rekrutacja białek CSA/CSB). Wspólny szlak: helikaza TFIIH (XPB, XPD) otwiera DNA → endonukleazy XPG (3') i XPF-ERCC1 (5') nacinają ~24-32 nt wokół uszkodzenia → Pol δ/ε syntetyzuje nowy fragment → ligaza. Mutacje w genach NER → Xeroderma pigmentosum (skrajna wrażliwość na UV, >1000× zwiększone ryzyko raka skóry, często z objawami neurologicznymi) – 7 genów komplementacji (XP-A do G), wariant XP-V (polimeraza η).
4. Naprawa błędnie sparowanych zasad (MMR – Mismatch Repair): naprawia błędy replikacji (niewłaściwe pary zasad A-C, G-T) i małe pętle insercyjno-delecyjne (IDLs). Białka MutSα (MSH2-MSH6, rozpoznaje błędne pary) i MutLα (MLH1-PMS2, koordynuje naprawę) → endonukleaza EXO1 usuwa fragment zawierający błąd → Pol δ → ligaza. Rozróżnienie starej nici (prawidłowej) od nowej (z błędem): u E. coli metylacja Dam (adenina w GATC); u eukariotów mechanizm mniej poznany, prawdopodobnie przez nacięcia (nicki) w nowej nici. Mutacje w MMR → dziedziczny rak jelita grubego bez polipowatości (HNPCC, zespół Lyncha), zwiększone ryzyko raka endometrium, żołądka, jajnika.
5. Naprawa pęknięć dwuniciowych (DSB – Double-Strand Break Repair): NHEJ (Non-Homologous End Joining) – szybkie łączenie końców, niezależne od homologii, często mutagienne (małe delecje/insercje). Ku70/Ku80 wiążą końce → DNA-PKcs (kinaza) → artemida (procesowanie końców) → ligaza IV + XRCC4 + XLF. Dominujący mechanizm w fazie G1. HR (Homologous Recombination) – wykorzystanie siostrzanej chromatydy jako matrycy, bezbłędna. Zachodzi głównie w fazie S/G2 (gdy dostępna jest siostrzana chromatyda). ATM (kinaza) wykrywa DSB → fosforylacja histonu H2AX (γH2AX) → rekrutacja BRCA1, BRCA2, RAD51. BRCA1/2 – geny supresorowe nowotworów; mutacje → dziedziczny rak piersi i jajnika (HBOC). RAD51 – rekombinaza, tworzy filament na jednoniciowym DNA, przeprowadza inwazję nici i wymianę nici → synteza naprawcza → ligaza.

BIOTECHNOLOGIA MOLEKULARNA – TECHNIKI LABORATORYJNE I ZASTOSOWANIA:
PCR (Polymerase Chain Reaction, Kary Mullis 1983, Nagroda Nobla 1993): Amplifikacja DNA in vitro. Składniki: matryca DNA, 2 startery (primers, ~18-25 nt, komplementarne do końców amplifikowanego fragmentu), polimeraza Taq (z Thermus aquaticus, termostabilna, optimum 72-80°C, dodawana w nadmiarze), dNTP (mieszanina dATP, dGTP, dCTP, dTTP), bufor z Mg²⁺ (kofaktor polimerazy). Cykle (25-35×): Denaturacja (95°C, 30s) → hybrydyzacja starterów (50-65°C, 30s, temperatura zależy od Tm starterów) → wydłużanie/elongacja (72°C, 1 min/1000 pz). Amplifikacja wykładnicza: N = N₀ × 2ⁿ po n cyklach. Warianty: RT-PCR (odwrotna transkryptaza → cDNA → PCR), qPCR (ilościowy PCR w czasie rzeczywistym – SYBR Green I lub sondy TaqMan), RT-qPCR (odwrotna transkrypcja + qPCR, standard do pomiaru ekspresji genów), ddPCR (cyfrowy PCR kropelkowy – bezwzględna kwantyfikacja bez krzywej standardowej).
Sekwencjonowanie DNA: Metoda Sangera (dideoksy, 1977, Nagroda Nobla 1980): synteza nici z ddNTP (dideoksynukleotydy – brak grupy 3'-OH → terminacja łańcucha). 4 oddzielne reakcje (po jednym ddNTP) + elektroforeza kapilarna → chromatogram (kolorowe piki odpowiadające nukleotydom). Odczyt do ~800-1000 pz. NGS (Next-Generation Sequencing, masowo równoległe sekwencjonowanie): Illumina (Sekwencjonowanie przez syntezę, mostkowe amplifikowanie na flow cell, odwracalne terminatory, ~150-300 pz odczyt, ~99,9% dokładność, najpopularniejsza platforma). Oxford Nanopore (bezpośredni odczyt pojedynczej cząsteczki DNA przechodzącej przez nanopor białkowy, zmiana prądu jonowego → identyfikacja nukleotydów; odczyty do >1 Mb, ale niższa dokładność ~95-98%; przenośny sekwenator MinION wielkości pendrive'a).
CRISPR-Cas9 (Nagroda Nobla z Chemii 2020, Emmanuelle Charpentier i Jennifer Doudna): bakteryjny system obrony przeciwwirusowej zaadaptowany do precyzyjnej edycji genomów. Komponenty: białko Cas9 (endonukleaza, wytwarza dwuniciowe pęknięcia DNA) + sgRNA (single guide RNA – fuzyjny konstrukt crRNA + tracrRNA, ~20 nt region komplementarny do docelowej sekwencji DNA). Warunek: obecność sekwencji PAM (Protospacer Adjacent Motif, dla SpCas9: NGG) obok docelowej sekwencji. Dwie domeny nukleazowe Cas9 (HNH – przecina nić komplementarną do sgRNA; RuvC – przecina nić niekomplementarną). Po DSB: NHEJ (tworzy insercyjno-delecyjne mutacje – wykorzystywane do knock-out genów) lub HDR z dostarczonym matrycowym DNA (precyzyjne wstawianie sekwencji – knock-in). Zastosowania: badania podstawowe (modelowanie chorób), terapia genowa (leczenie anemii sierpowatej – edycja genu BCL11A w komórkach macierzystych hematopoezy), rolnictwo (odmiany odporne na choroby), biotechnologia. Wyzwania: efekty poza-celem (off-target), immunogenność Cas9 (bakteryjne pochodzenie), etyka edycji zarodków (kontrowersje po eksperymencie He Jiankui, 2018 – edycja CCR5 w ludzkich zarodkach)."""

print("Biology expansion content modules loaded.")
print(f"Cytologia extra: {len(BIOLOGY_EXTRA_CYTOLOGIA):,} chars")
print(f"Metabolizm extra: {len(BIOLOGY_EXTRA_METABOLIZM):,} chars")
print(f"Genetyka extra: {len(BIOLOGY_EXTRA_GENETYKA):,} chars")
