# Expansion script for biology, chemistry, and anatomy textbook data files
# This script massively expands the existing data files with full textbook content

import os

BASE = r"C:\DAWID_PRACE\Anatomia\anatomy-3d\src\data"

# =====================================================================
# MASSIVE BIOLOGY EXPANSION CONTENT
# =====================================================================

BIOLOGY_EXPANDED_CYTOLOGIA = """Komórka (cellula) jest podstawową jednostką strukturalną i funkcjonalną organizmów żywych, zdolną do samodzielnego przeprowadzania wszystkich procesów życiowych: odżywiania, oddychania, wzrostu, rozmnażania i reakcji na bodźce. Nauka o komórce – cytologia (biologia komórki) – stanowi fundament współczesnej biologii i medycyny.

TEORIA KOMÓRKOWA (Schleiden 1838, Schwann 1839, Virchow 1855):
1. Wszystkie organizmy zbudowane są z komórek.
2. Komórka jest podstawową jednostką strukturalną i funkcjonalną życia.
3. Każda komórka powstaje wyłącznie z innej komórki (omnis cellula e cellula – Virchow).
4. Komórki zawierają informację dziedziczną (DNA), która jest przekazywana podczas podziału.
5. Wszystkie reakcje metaboliczne zachodzą wewnątrz komórek.

Znaczenie historyczne: Robert Hooke (1665) – pierwsza obserwacja komórek (korek); Antonie van Leeuwenhoek (1674) – pierwsze obserwacje żywych komórek (pierwotniaki, bakterie); Robert Brown (1831) – odkrycie jądra komórkowego; Rudolf Virchow (1855) – "omnis cellula e cellula".

WSPÓŁCZESNA KLASYFIKACJA ORGANIZMÓW (system trzech domen, Woese 1990):
Domena Bacteria (Eubacteria) – właściwe bakterie, ściana komórkowa z mureiny (peptydoglikanu).
Domena Archaea (Archeowce) – ściana komórkowa z pseudomureiny, błona z eterowych lipidów (izoprenoidy), ekstremofile (halofile, termofile, metanogeny).
Domena Eukarya (Eukarionty) – Protista, Fungi, Plantae, Animalia.

TYPY KOMÓREK – ANALIZA PORÓWNAWCZA:
Komórki prokariotyczne: wielkość 0,5-10 μm; nukleoid (kolista, nieosłonięta cząsteczka DNA, ułożona w pętle, związana z białkami niehistonowymi); brak jądra i organelli błoniastych; rybosomy 70S (podjednostki 50S + 30S); ściana komórkowa – Bacteria: mureina (peptydoglikan – łańcuchy N-acetyloglukozaminy i kwasu N-acetylomuraminowego usieciowane mostkami peptydowymi), Archaea: pseudomureina; podział przez amitozę (rozszczepienie binarne – replikacja DNA + przewężenie błony i ściany); plazmidy – małe, koliste cząsteczki DNA poza chromosomem (oporność na antybiotyki); fimbrie i pile – struktury białkowe do adhezji i koniugacji; rzęska bakteryjna – zbudowana z flageliny, napędzana rotacyjnie przez gradient protonowy (nie ma struktury 9+2!).

Komórki eukariotyczne: wielkość 10-100 μm (wyjątkowo komórka jajowa strusia ~10 cm, niektóre neurony >1 m); jądro komórkowe otoczone podwójną błoną (envelope jądrowa) z kompleksami porowymi (NPC – Nuclear Pore Complex, selektywny transport); organelle błoniaste (system błon wewnątrzkomórkowych – ER, Golgi, lizosomy, endosomy, peroksysomy); rybosomy 80S (60S + 40S) w cytozolu oraz 70S w mitochondriach i chloroplastach; podział przez mitozę (wzrost) i mejozę (rozmnażanie płciowe); cytoszkielet (mikrofilamenty, filamenty pośrednie, mikrotubule); egzocytoza i endocytoza (transport pęcherzykowy).

SKŁAD CHEMICZNY KOMÓRKI – ANALIZA ILOŚCIOWA I FUNKCJONALNA:
Woda (70-85% masy komórki): polarne środowisko, wysoka stała dielektryczna (ε≈80); doskonały rozpuszczalnik dla związków jonowych i polarnych; reagent w reakcjach hydrolizy i fotolizie H2O (fotosynteza); wysokie ciepło właściwe (4,18 J/g·K) – termoregulacja; wysokie ciepło parowania (2260 J/g) – ochładzanie przez transpirację i pocenie; gęstość maksymalna w 4°C (lód pływa – izolacja termiczna zbiorników wodnych); kohezja i adhezja – transport wody w naczyniach ksylemu; napięcie powierzchniowe – umożliwia poruszanie się organizmów po powierzchni wody.

Białka (10-20% masy): polimery aminokwasów połączone wiązaniami peptydowymi (-CO-NH-). 20 standardowych aminokwasów białkowych (α-aminokwasy o konfiguracji L w białkach). Poziomy organizacji strukturalnej:
- Struktura I-rzędowa: sekwencja aminokwasów w łańcuchu polipeptydowym (wiązania peptydowe). Determinuje wszystkie wyższe poziomy struktury.
- Struktura II-rzędowa: lokalne uporządkowanie przestrzenne – α-helisa (wiązania wodorowe CO z HN co 4 reszty, 3,6 reszty na skręt, skok 0,54 nm), β-harmonijka (wiązania wodorowe między odległymi fragmentami łańcucha, równoległa lub antyrównoległa), skręt β (zwrot β – 4 reszty, mostek wodorowy), pętle i regiony nieuporządkowane.
- Struktura III-rzędowa: pełna konformacja przestrzenna jednego łańcucha. Stabilizowana przez: mostki disiarczkowe (-S-S- między cysteinami), wiązania wodorowe, oddziaływania jonowe (mostki solne), oddziaływania hydrofobowe (główna siła napędowa fałdowania), oddziaływania van der Waalsa.
- Struktura IV-rzędowa: asocjacja kilku podjednostek (np. hemoglobina – tetramer α2β2; dehydrogenaza mleczanowa – tetramer).
Klasyfikacja funkcjonalna białek:
- Enzymatyczna: kataliza reakcji biochemicznych (polimeraza DNA, heksokinaza, pepsyna, RuBisCO).
- Strukturalna: budulec tkanek (kolagen – główne białko tkanki łącznej, potrójna helisa; keratyna – włosy, paznokcie, naskórek; elastyna – więzadła, ściany tętnic).
- Transportowa: hemoglobina (O2 we krwi), mioglobina (O2 w mięśniach), albuminy (kwasy tłuszczowe, leki, hormony), transferyna (Fe3+).
- Odpornościowa: immunoglobuliny (przeciwciała – IgG, IgM, IgA, IgE, IgD), układ dopełniacza, interleukiny.
- Ruchowa/kurczliwa: aktyna i miozyna (skurcz mięśni), dyneina i kinezyna (transport wzdłuż mikrotubul), tubulina (polimeryzacja).
- Sygnałowa/hormonalna: insulina (metabolizm glukozy), glukagon, hormon wzrostu (GH), erytropoetyna (EPO).
- Regulatorowa: czynniki transkrypcyjne (wiązanie DNA), histony (pakowanie DNA), ubikwityna (znakowanie białek do degradacji).
- Zapasowa: albumina jaja kurzego (owoalbumina), kazeina mleka, ferrytyna (magazyn Fe).

Denaturacja białka – utrata struktury II-, III- i IV-rzędowej pod wpływem: temperatury (>50-60°C), skrajnego pH, rozpuszczalników organicznych, detergentów, jonów metali ciężkich. Denaturacja nie narusza struktury I-rzędowej. Renaturacja – spontaniczne odzyskanie natywnej konformacji (doświadczenie Anfinsena, 1957, Nagroda Nobla 1972 – rybonukleaza A zdenaturowana mocznikiem i β-merkaptoetanolem odzyskuje aktywność po usunięciu czynników denaturujących).

Węglowodany (cukry, sacharydy): związki o ogólnym wzorze Cn(H2O)n.
Monosacharydy: glukoza C6H12O6 – aldoheksoza, główne paliwo komórkowe; fruktoza – ketoheksoza; galaktoza – aldoheksoza, składnik laktozy; ryboza – aldopentoza, składnik RNA; deoksyryboza – składnik DNA (brak grupy -OH przy C2). W roztworze monosacharydy występują głównie w formie pierścieniowej (hemiacetal/hemiketal – reakcja grupy karbonylowej z grupą OH). Anomery α i β – różne położenie grupy OH przy anomerycznym atomie węgla (C1 u aldoz, C2 u ketoz). Mutarotacja – zmiana skręcalności optycznej roztworu w wyniku ustalania się równowagi między formami α i β.
Disacharydy (wiązanie O-glikozydowe między dwoma monosacharydami): sacharoza (glukoza-α-1,2-fruktoza – cukier spożywczy, nieredukująca, hydroliza → cukier inwertowany), laktoza (galaktoza-β-1,4-glukoza – cukier mleczny, redukująca), maltoza (glukoza-α-1,4-glukoza – cukier słodowy, redukująca, produkt hydrolizy skrobi), celobioza (glukoza-β-1,4-glukoza – produkt hydrolizy celulozy, redukująca).
Polisacharydy: skrobia – magazyn energii u roślin (amyloza – nierozgałęziona, helisa α-1,4-glukozy, barwi się z jodem na granatowo; amylopektyna – rozgałęziona co 24-30 reszt wiązaniami α-1,6); glikogen – magazyn energii u zwierząt i grzybów (podobny do amylopektyny, ale silniej rozgałęziony co 8-12 reszt, magazynowany w wątrobie i mięśniach); celuloza – β-1,4-glukoza, prosty łańcuch (wiązania β umożliwiają tworzenie długich, sztywnych włókien – micele celulozowe), główny składnik ściany komórkowej roślin; chityna – β-1,4-N-acetyloglukozamina, ściana komórkowa grzybów, szkielet zewnętrzny stawonogów; inulina – fruktoza, magazyn u niektórych roślin (np. dalia, topinambur); agar – ściana komórkowa krasnorostów; mureina (peptydoglikan) – ściana komórkowa bakterii.

Lipidy – związki hydrofobowe, rozpuszczalne w rozpuszczalnikach organicznych:
Tłuszcze właściwe (triacyloglicerole, triglicerydy): triestry glicerolu z trzema kwasami tłuszczowymi. Kwasy nasycone (C-C, stałe w temp. pokojowej: kwas palmitynowy C16:0, stearynowy C18:0) i nienasycone (C=C, ciekłe: kwas oleinowy C18:1 ω-9, linolowy C18:2 ω-6, α-linolenowy C18:3 ω-3). NNKT – Niezbędne Nienasycone Kwasy Tłuszczowe (kwas linolowy i α-linolenowy – organizm człowieka nie potrafi ich syntetyzować, muszą być dostarczane w diecie). Funkcje: magazyn energii (najbardziej wydajny – 38 kJ/g vs 17 kJ/g z węglowodanów/białek), izolacja termiczna (tkanka tłuszczowa podskórna), amortyzacja mechaniczna (wokół narządów), rozpuszczalnik witamin A, D, E, K.
Fosfolipidy: glicerol + 2 kwasy tłuszczowe + reszta fosforanowa + grupa polarna (cholinoamina, seryna, inozytol). Amfipatyczny charakter (hydrofilowa głowa + hydrofobowy ogon) – podstawa struktury błon biologicznych. Fosfatydylocholina (lecytyna) – główny fosfolipid błon komórkowych zwierząt.
Steroidy: cholesterol – składnik błon komórkowych zwierząt (moduluje płynność błony, prekursor hormonów steroidowych i kwasów żółciowych); hormony płciowe (testosteron, estradiol, progesteron); hormony kory nadnerczy (kortyzol, aldosteron); witamina D (kalcyferol) – gospodarka Ca2+ i P; kwasy żółciowe (emulsyfikacja tłuszczów w dwunastnicy).
Woski: estry wyższych kwasów tłuszczowych z wyższymi alkoholami jednowodorotlenowymi. Hydrofobowe – ochrona przed utratą wody (kutykula liści, pióra ptaków, sierść ssaków, egzoszkielet owadów).
Karotenoidy: barwniki izoprenowe – β-karoten (prowitamina A), likopen (pomidory), luteina, zeaksantyna. Chronią przed fotooksydacją, akcesoryjne barwniki fotosyntetyczne.

Kwasy nukleinowe – nośniki i pośredniki informacji genetycznej:
DNA (kwas deoksyrybonukleinowy): nukleotyd = deoksyryboza + reszta fosforanowa(V) + zasada azotowa (A – adenina, G – guanina, C – cytozyna, T – tymina). Podwójna prawoskrętna helisa (forma B-DNA – 10 par zasad na skręt, skok 3,4 nm, średnica 2 nm; w warunkach odwodnienia forma A-DNA). Wiązania fosfodiestrowe łączą nukleotydy w łańcuch (wiązanie 3'-5' – między grupą 3'-OH deoksyrybozy a 5'-fosforanem następnego nukleotydu). Kierunek: 5' → 3'.
RNA (kwas rybonukleinowy): ryboza zamiast deoksyrybozy, uracyl (U) zamiast tyminy (T). Jednoniciowy (choć może tworzyć struktury II-rzędowe – spinki do włosów, pseudowęzły). Rodzaje: mRNA (matrycowy/informacyjny – kopia genu, 3-5% całkowitego RNA), tRNA (transportowy – przenosi aminokwasy na rybosom, 15%, struktura koniczynki, 70-90 nukleotydów), rRNA (rybosomowy – 80%, składnik strukturalny i katalityczny rybosomów), snRNA (mały jądrowy – splicing), miRNA i siRNA (regulacja ekspresji genów, interferencja RNA), lncRNA (długie niekodujące RNA – regulacja epigenetyczna), rybozymy (RNA o aktywności katalitycznej – np. 23S rRNA w rybosomie, RNAza P).
Reguły Chargaffa (1950): [A] = [T], [G] = [C]; [A] + [G] = [T] + [C] (stosunek puryn do pirymidyn = 1); skład zasad jest charakterystyczny dla gatunku, ale stały we wszystkich komórkach danego organizmu.

Sole mineralne i ich fizjologiczne znaczenie:
Makroelementy: Na+ (główny kation zewnątrzkomórkowy – 140 mmol/L, potencjał błonowy, transport substancji odżywczych – kotransport Na+/glukoza); K+ (główny kation wewnątrzkomórkowy – 140 mmol/L wewnątrz vs 5 mmol/L zewnątrz, repolaryzacja neuronów, pompa Na+/K+ – zużywa ~30% ATP komórki); Ca2+ (skurcz mięśni – łączy się z troponiną; krzepnięcie krwi – kaskada krzepnięcia, czynnik IV; neurotransmisja – egzocytoza pęcherzyków synaptycznych; wtórny przekaźnik sygnału – kalmodulina, IP3; składnik hydroksyapatytu Ca10(PO4)6(OH)2 w kościach i zębach – 99% Ca2+ organizmu); Mg2+ (centralny atom chlorofilu, kofaktor >300 enzymów – kinazy, ATPazy, polimerazy); Fe2+/Fe3+ (hem – wiązanie O2 w hemoglobinie i mioglobinie; centra żelazowo-siarkowe i cytochromy – łańcuch oddechowy; katalaza, peroksydaza – rozkład H2O2); PO4 3- (wiązania wysokoenergetyczne ATP – fosfoestrowe i fosfodiestrowe; składnik kwasów nukleinowych; składnik hydroksyapatytu; bufory fosforanowe wewnątrz komórki); HCO3- (główny bufor osocza krwi – układ buforowy H2CO3/HCO3-, utrzymuje pH krwi 7,35-7,45); Cl- (główny anion zewnątrzkomórkowy, równowaga ładunku, HCl w soku żołądkowym).
Mikroelementy (śladowe, <0,01% masy): I (składnik hormonów tarczycy T3 i T4 – niedobór → wole endemiczne), Zn (kofaktor ~100 enzymów, palce cynkowe w czynnikach transkrypcyjnych), Cu (składnik oksydazy cytochromowej, tyrozynazy – synteza melaniny, ceruloplazminy), Mn (aktywator wielu enzymów, fotoliza H2O w PSII), Co (centralny atom witaminy B12 – kobalamina, dojrzewanie erytrocytów), Se (selenocysteina – 21. aminokwas białkowy, peroksydaza glutationowa – ochrona antyoksydacyjna), F (fluoroapatyt w szkliwie zębów – odporność na próchnicę), Mo (kofaktor oksydazy ksantynowej, nitrogenazy).

BŁONA KOMÓRKOWA – MODEL MOZAIKOWY PŁYNNY (Sanger i Nicolson, 1972):
Podstawowa architektura: podwójna warstwa fosfolipidowa (ang. lipid bilayer) – fosfolipidy spontanicznie układają się w dwuwarstwę (hydrofobowe ogony do wewnątrz, hydrofilowe głowy na zewnątrz i do wnętrza komórki). Grubość ~7-8 nm.
Asymetria błony: zewnętrzna warstwa – głównie fosfatydylocholina i sfingomielina; wewnętrzna (cytoplazmatyczna) warstwa – fosfatydyloseryna (ujemny ładunek, sygnał apoptozy) i fosfatydyloetanoloamina.
Płynność błony zależy od: długości i stopnia nienasycenia łańcuchów kwasów tłuszczowych (krótsze i bardziej nienasycone → większa płynność); ilości cholesterolu (u zwierząt – przy niskich temperaturach zapobiega krystalizacji, przy wysokich ogranicza nadmierną płynność, działa jak bufor płynności); temperatury (wzrost T → wzrost płynności).
Białka błonowe: integralne (transbłonowe – α-helisy hydrofobowe, 1-, 7- lub wielokrotnie przechodzące przez błonę, często glikozylowane; np. receptory GPCR – 7 helis transbłonowych, kanały jonowe, pompy, transportery); peryferyjne (związane z powierzchnią błony oddziaływaniami jonowymi i wodorowymi, łatwo usuwalne; np. spektryna, ankiryna w erytrocytach – utrzymują dwuwklęsły kształt); zakotwiczone lipidowo (kowalencyjnie związane z lipidem błonowym – GPI, prenylacja, palmitylacja).
Tratwy lipidowe (lipid rafts) – mikrodomeny błonowe bogate w cholesterol i sfingolipidy, uporządkowane, skupiają specyficzne białka (receptory, kanały, białka sygnałowe).
Glikokaliks – warstwa łańcuchów cukrowych (oligosacharydów) na zewnętrznej powierzchni błony, przyłączonych do białek (glikoproteiny) i lipidów (glikolipidy). Funkcje: ochrona mechaniczna i chemiczna, rozpoznanie międzykomórkowe (antygeny grupowe krwi AB0 – glikosfingolipidy), adhezja komórek, udział w odpowiedzi immunologicznej (MHC, przeciwciała).

TRANSPORT PRZEZ BŁONY BIOLOGICZNE:
Transport bierny (zgodnie z gradientem stężenia/elektrochemicznym, bez nakładu energii metabolicznej):
- Dyfuzja prosta: przez dwuwarstwę lipidową – małe cząsteczki niepolarne (O2, CO2, N2), małe cząsteczki polarne nieobdarzone ładunkiem (H2O – przez akwaporyny, mocznik, etanol), lipofilowe (hormony steroidowe, kwasy tłuszczowe). Szybkość zależy od gradientu stężeń, współczynnika podziału olej/woda, wielkości cząsteczki.
- Dyfuzja ułatwiona: przez kanały białkowe (pory błonowe): kanały jonowe bramkowane napięciem (Na+, K+, Ca2+ w neuronach i mięśniach), bramkowane ligandem (receptor nikotynowy ACh – kanał Na+, receptor GABA – kanał Cl-), bramkowane mechanicznie (mechanoreceptory w skórze, komórki włoskowate ucha wewnętrznego); przez kotransportery/przenośniki (zmiana konformacji białka bez hydrolizy ATP): GLUT1-GLUT4 (transport glukozy – GLUT4 insulinowrażliwy w mięśniach i tkance tłuszczowej), białko pasmowe 3 w erytrocytach (wymiana Cl-/HCO3-).
- Osmoza: przepływ wody przez błonę półprzepuszczalną z roztworu o niższym stężeniu osmotycznym do roztworu o wyższym stężeniu. Akwaporyny (AQP) – kanały wodne białkowe (AQP-1 w erytrocytach i kanalikach proksymalnych nerki; AQP-2 w kanalikach zbiorczych – regulowany przez ADH). Roztwór: izotoniczny (0,9% NaCl – sól fizjologiczna, 5% glukoza), hipotoniczny (pęcznienie → hemoliza), hipertoniczny (kurczenie → plazmoliza w komórkach roślinnych, krenacja erytrocytów).

Transport aktywny (przeciwnie do gradientu, wymaga energii metabolicznej – bezpośrednio ATP lub pośrednio gradient jonowy):
- Pierwotny transport aktywny: pompa Na+/K+-ATPaza – 3 Na+ na zewnątrz, 2 K+ do wnętrza na 1 hydrolizowaną cząsteczkę ATP, elektrogeniczna (wyprowadza +1 ładunek netto na cykl, przyczynia się do potencjału spoczynkowego -70 mV), hamowana przez ouabainę i glikozydy nasercowe (digitalis – wzmacniają skurcz serca przez zwiększenie [Na+] wewnątrz → hamowanie wymiennika Na+/Ca2+ → wzrost [Ca2+]); pompa Ca2+-ATPaza (SERCA w retikulum sarkoplazmatycznym i PMCA w błonie komórkowej – utrzymuje [Ca2+]cytozol ~100 nM, 10 000× mniej niż na zewnątrz); pompa H+-ATPaza (w błonie lizosomów i wakuoli – zakwaszanie wnętrza); pompa H+/K+-ATPaza (komórki okładzinowe żołądka – wydzielanie HCl).
- Wtórny transport aktywny (kotransport, sprzężony): wykorzystuje gradient Na+ (lub H+) wytworzony przez pompę Na+/K+. Symport (substancje transportowane w tym samym kierunku co Na+): SGLT (kotransport Na+/glukoza w jelicie i nerce), Na+/aminokwas. Antyport (wymiana przeciwkierunkowa): wymiennik Na+/Ca2+ (NCX – usuwa Ca2+ z kardiomiocytów podczas rozkurczu), wymiennik Na+/H+ (regulacja pH).
- Endocytoza: fagocytoza (pochłanianie dużych cząstek – bakterie, resztki komórkowe; makrofagi, neutrofile; pseudopodia → fagosom + lizosom → fagolizosom); pinocytoza (pobieranie płynów z rozpuszczonymi substancjami – stała, niespecyficzna); endocytoza zależna od receptorów (za pośrednictwem klatryny w dołkach opłaszczonych – LDL, transferyna, hormony białkowe; kaweolina – kaweosomy).
- Egzocytoza: konstytutywna (ciągłe wydzielanie – białka macierzy zewnątrzkomórkowej, przeciwciała przez plazmocyty) i regulowana (wydzielanie na sygnał – neurotransmitery, insulina, histamina z mastocytów). Pęcherzyki opłaszczone białkami COP I, COP II, klatryną.

SYGNALIZACJA KOMÓRKOWA (KOMUNIKACJA MIĘDZYKOMÓRKOWA):
Rodzaje komunikacji: endokrynowa (hormony do krwi – daleki zasięg), parakrynowa (lokalne mediatory – histamina, prostaglandyny, NO), autokrynowa (komórka odpowiada na własny sygnał – limfocyty T, komórki nowotworowe), synaptyczna (neurotransmitery w synapsach – bardzo szybka, precyzyjna), juxtakrynna (przez bezpośredni kontakt – białka błonowe, złącza szczelinowe/neksus).
Szlak sygnałowy: ligand (pierwotny przekaźnik) → receptor → przetwornik → wtórne przekaźniki (cAMP, IP3, DAG, Ca2+, cGMP) → kinazy białkowe → fosforylacja białek efektorowych → odpowiedź komórkowa.
Receptory: błonowe (powierzchniowe) – dla ligandów hydrofilowych (hormony białkowe, neurotransmitery, czynniki wzrostu). Typy: GPCR (receptory sprzężone z białkiem G – 7 domen transbłonowych; białko G – trimer αβγ, wiąże GTP/GDP; αs – pobudza cyklazę adenylanową → cAMP↑; αi – hamuje → cAMP↓; αq – aktywuje fosfolipazę C → IP3 + DAG → Ca2+↑ + kinaza białkowa C); RTK (receptorowe kinazy tyrozynowe – dimeryzacja po związaniu ligandu → autofosforylacja tyrozyn → kaskada Ras-MAPK → proliferacja, różnicowanie; insulina, EGF, PDGF); receptory jonotropowe (kanały jonowe bramkowane ligandem – nikotynowy receptor ACh, receptor NMDA/AMPA dla glutaminianu, receptor GABAA dla GABA); receptory wewnątrzkomórkowe – dla ligandów hydrofobowych przechodzących przez błonę (hormony steroidowe – receptor w cytozolu, po związaniu przechodzi do jądra; hormony tarczycy – receptor już w jądrze związany z DNA; działają jako czynniki transkrypcyjne, regulują ekspresję genów).

POŁĄCZENIA MIĘDZYKOMÓRKOWE (JUNKCJE):
Złącze ścisłe (tight junction, zonula occludens): uszczelnienie przestrzeni międzykomórkowej (białka: klaudyny, okludyny, JAM), selektywna bariera parakomórkowa, oddziela domenę apikalną od bazolateralnej (polaryzacja komórek nabłonka). Np. nabłonek jelita, bariera krew-mózg.
Złącze przylegania (zonula adherens): kadheryny łączą się z filamentami aktynowymi przez kateniny. Pasmo przylegania w komórkach nabłonka.
Desmosom (macula adherens): kadheryny (desmogleina, desmokolina) łączą się z filamentami pośrednimi (keratyna) przez płytkę desmosomalną. Silne mechanicznie. Np. w naskórku, mięśniu sercowym (wstawki).
Złącze szczelinowe (gap junction, nexus, neksus): koneksony (6 koneksyn tworzy półkanał w jednej komórce, dwa półkanały się łączą) – bezpośrednie połączenie cytoplazm sąsiednich komórek. Przepływ jonów, metabolitów, wtórnych przekaźników (cAMP, Ca2+). Szybka komunikacja elektryczna i metaboliczna. Np. synapsy elektryczne, mięsień sercowy (szybkie rozchodzenie się potencjału czynnościowego), mięśniówka gładka.
Hemiesmosom: łączy komórkę z błoną podstawną (integryny + filamenty pośrednie).
Plazmodesmy (rośliny): kanały w ścianie komórkowej łączące protoplasty, przez które przechodzi retikulum endoplazmatyczne (desmotubula). Transport symplastowy.

MACIERZ ZEWNĄTRZKOMÓRKOWA (ECM):
Składniki: białka włókniste – kolagen (typ I – kości, skóra, ścięgna; typ II – chrząstka; typ III – tkanka siateczkowata; typ IV – błona podstawna), elastyna (sprężystość), fibronektyna (adhezja, łączy komórki z ECM przez integryny), laminina (główny składnik błony podstawnej); proteoglikany (rdzeń białkowy + łańcuchy GAG – kwas hialuronowy, siarczan chondroityny, siarczan heparanu) – tworzą żel, wiążą wodę i czynniki wzrostu. Integryny – receptory komórkowe dla ECM, dwukierunkowa sygnalizacja (inside-out i outside-in).

ORGANELLE KOMÓRKOWE – SZCZEGÓŁOWA CHARAKTERYSTYKA:

Jądro komórkowe (nucleus): średnica 5-10 μm. Otoczone podwójną błoną (envelope jądrowa – zewnętrzna błona ciągła z RER, wewnętrzna związana z laminą jądrową). Kompleksy poru jądrowego (NPC – Nuclear Pore Complex): ~30 różnych białek (nukleoporyny), masa ~125 MDa, ~3000-4000 porów/jądro. Transport pasywny dla cząsteczek <40 kDa, aktywny (importyny/eksportyny, zależny od Ran GTPazy) dla większych. Jąderko – miejsce syntezy rRNA (geny rDNA na chromosomach akrocentrycznych 13, 14, 15, 21, 22) i formowania podjednostek rybosomów. Chromatyna: nukleosom (oktamer histonowy: H2A, H2B, H3, H4 – po 2 cząsteczki, ~147 pz DNA nawiniętego w 1,67 zwoju) + łącznikowy DNA + histon H1 (uszczelnienie, tworzenie włókna 30 nm solenoidu/zig-zag). Euchromatyna – mniej skondensowana, transkrypcyjnie aktywna, acetylacja histonów (HAT – aktywacja). Heterochromatyna – silnie skondensowana, nieaktywna; konstytutywna (centromery, telomery – zawsze nieaktywna) i fakultatywna (nieaktywny chromosom X – ciałko Barra u kobiet). Kariotyp człowieka: 2n = 46 (22 pary autosomów metacentrycznych/submetacentrycznych/akrocentrycznych + 1 para chromosomów płci XX lub XY). Badanie kariotypu – hodowla limfocytów, zatrzymanie w metafazie (kolchicyna), barwienie (prążki G – Giemsa).

Rybosomy: nieobłoniona struktura rybonukleoproteinowa. U eukariotów: podjednostka duża 60S (28S rRNA, 5,8S rRNA, 5S rRNA, ~49 białek), mała 40S (18S rRNA, ~33 białka) → cały rybosom 80S. Miejsca wiążące tRNA: A (aminoacylo-tRNA), P (peptydylo-tRNA), E (exit). Peptydylotransferaza – aktywność katalityczna 28S rRNA (rybozym!). Rybosomy mitochondrialne: 55S (podobne do bakteryjnych). Polirybosomy (polisomy) – wiele rybosomów na jednej nici mRNA.

Retikulum endoplazmatyczne (ER):
RER (szorstkie): pokryte rybosomami, synteza białek na eksport (sekwencja sygnałowa N-końcowa kieruje rybosom do translokonu Sec61 w błonie RER → kotranslacyjna translokacja do światła RER → odcięcie peptydu sygnałowego przez peptydazę sygnałową → fałdowanie z udziałem chaperonów BiP, kalneksyna, kalretikulina → N-glikozylacja → transport do Golgiego pęcherzykami COP II), synteza białek błonowych i lizosomalnych.
SER (gładkie): synteza lipidów (fosfolipidy, cholesterol, steroidy), detoksykacja w wątrobie (rodzina cytochromu P450 – utlenianie ksenobiotyków, leków, alkoholu → hydroksylacja → sprzęganie z kwasem glukuronowym → wydalanie); magazyn Ca2+ w mięśniach (retikulum sarkoplazmatyczne – SERCA pompuje Ca2+ do środka, kanały rianodynowe RyR uwalniają Ca2+ przy pobudzeniu → skurcz); metabolizm węglowodanów (glukozo-6-fosfataza w wątrobie – uwalnianie glukozy do krwi).

Aparat Golgiego: spolaryzowany stos spłaszczonych cystern. Cis-Golgi (strona wejściowa, od strony RER) → medial-Golgi → trans-Golgi (strona wyjściowa, do błony/lizosomów). Modyfikacje: glikozylacja (N-glikozylacja rozpoczyna się w RER, O-glikozylacja zachodzi w Golgim); fosforylacja białek lizosomalnych (znacznik mannozo-6-fosforan → rozpoznanie przez receptor M6P w trans-Golgi); sortowanie i pakowanie do pęcherzyków; synteza polisacharydów ściany komórkowej (pektyny, hemiceluloza). Transport: model dojrzewania cystern (cis→trans) vs transport pęcherzykowy (anterogradowy i retrogradowy między cysternami).

Mitochondria: długość 2-8 μm, średnica 0,5-1 μm, liczba: od 1 (niektóre protisty) do kilkuset tysięcy (kardiomiocyty). Błona zewnętrzna gładka, przepuszczalna dla małych cząsteczek (<5 kDa) przez poryny (VDAC). Przestrzeń międzybłonowa (skład podobny do cytozolu). Błona wewnętrzna silnie pofałdowana (grzebienie mitochondrialne – cristae), nieprzepuszczalna dla jonów (wymaga transporterów), zawiera: łańcuch oddechowy (kompleksy I-IV), syntazę ATP (kompleks V), translokazę ATP/ADP, kardiolipinę (fosfolipid charakterystyczny dla błon bakteryjnych i wewnętrznej błony mitochondrialnej). Macierz mitochondrialna (matrix): enzymy cyklu Krebsa, β-oksydacji kwasów tłuszczowych, mtDNA (koliste, ~16 569 pz, 37 genów: 13 białek łańcucha oddechowego, 22 tRNA, 2 rRNA), rybosomy 70S, mtRNA polimeraza. Dziedziczenie mitochondrialne: wyłącznie po matce (mitochondria plemnika wnikają do komórki jajowej, ale są selektywnie degradowane – ubikwitynacja). Teoria endosymbiozy (Lynn Margulis, 1967): mitochondria pochodzą od tlenowych α-proteobakterii wchłoniętych przez przodka eukariota ~1,5 mld lat temu. Dowody: podwójna błona (wewnętrzna – bakteryjna, zewnętrzna – pęcherzyka fagocytarnego gospodarza), własne DNA koliste bez histonów, rybosomy 70S wrażliwe na chloramfenikol i tetracykliny (antybiotyki przeciwbakteryjne), namnażanie przez podział (fisja), kardiolipina w błonie wewnętrznej (bakteryjne pochodzenie), genom mitochondrialny bliższy α-proteobakteriom niż genomowi jądrowemu.

Chloroplasty: średnica 4-10 μm, soczewkowate. Otoczone podwójną błoną (chloroplastową zewnętrzną i wewnętrzną). Stroma – płynna macierz zawierająca enzymy cyklu Calvina, DNA chloroplastowe (koliste, ~120-160 kpz, ~100 genów), rybosomy 70S. Tylakoidy – spłaszczone pęcherzyki błonowe; tylakoidy gran (ułożone w stosy – grana) i tylakoidy stromy (łączą grana, eksponowane na stromę). Błona tylakoidu zawiera: fotosystemy (PSI, PSII), kompleks cytochromów b6f, syntazę ATP. Barwniki: chlorofil a (główny barwnik fotosyntetyczny, P680 w PSII, P700 w PSI – centra reakcji); chlorofil b (akcesoryjny, poszerza spektrum absorpcji); karotenoidy (β-karoten, luteina – barwniki pomocnicze, chronią przed fotooksydacją – cykl ksantofilowy). Teoria endosymbiozy: chloroplasty pochodzą od sinic (Cyanobacteria) wchłoniętych przez komórkę eukariotyczną ~1,2 mld lat temu. Endosymbioza pierwotna (sinica → chloroplast z 2 błonami u roślin, krasnorostów, zielenic) vs wtórna (komórka eukariotyczna z chloroplastem wchłonięta przez innego eukariota → chloroplast z 3-4 błonami u bruzdnic, okrzemek, brunatnic).

Lizosomy: pęcherzyki (0,1-1,2 μm) zawierające ~60 różnych enzymów hydrolitycznych (hydrolazy kwasowe). Optimum pH ~5 (utrzymywane przez pompę H+-ATPaza w błonie lizosomu). Enzymy: proteazy (katepsyny), nukleazy, glikozydazy, lipazy, fosfatazy, sulfatazy. Funkcje: trawienie wewnątrzkomórkowe materiału pobranego w endocytozie (endosom wczesny → późny → lizosom); autofagia – degradacja zużytych organelli (autofagosom + lizosom → autolizosom), kluczowe dla homeostazy komórki, odpowiedzi na głodzenie (Nagroda Nobla 2016, Yoshinori Ohsumi); apoptoza – kontrolowane uwalnianie katepsyn; krynofagia – degradacja ziarnistości wydzielniczych. Choroby spichrzeniowe (lizosomalne): choroba Pompego (brak kwaśnej α-glukozydazy → gromadzenie glikogenu), choroba Gauchera (brak β-glukocerebrozydazy), choroba Tay-Sachsa (brak heksozoaminidazy A → gromadzenie gangliozydów GM2 w neuronach).

Peroksysomy: pęcherzyki (0,1-1 μm) otoczone pojedynczą błoną. Enzymy oksydacyjne: oksydaza moczanowa (→ H2O2), oksydaza D-aminokwasowa, oksydaza α-hydroksykwasowa. Katalaza – rozkład H2O2 (2H2O2 → 2H2O + O2). β-oksydacja bardzo długich kwasów tłuszczowych (>C22). Biosynteza plazmalogenów (fosfolipidy eterowe – mielina). Biosynteza kwasów żółciowych (wątroba). Cykl glioksylanowy u roślin (przekształcanie tłuszczów w cukry podczas kiełkowania nasion). Powstają przez podział istniejących peroksysomów lub z ER.

Cytoszkielet – dynamiczna sieć białkowych włókien:
Mikrofilamenty (filamenty aktynowe, 7 nm): polimeryzacja aktyny G (globularna, wiąże ATP) w aktynę F (filamentarna) – spolaryzowana (koniec plus – szybka polimeryzacja, koniec minus – wolniejsza). Białka wiążące aktynę: miozyna (kurczliwość – sarkomery, cytokineza), tropomiozyna (stabilizuje filament), spektryna i dystrofina (związanie z błoną), filamina (wiązanie krzyżowe → sieci), ARP2/3 (rozgałęzienia), profilina (wymiana ADP→ATP), kofilina (depolimeryzacja). Funkcje: skurcz mięśni (wraz z miozyną II – sarkomery), cytokineza (pierścień kurczliwy), ruchy pełzakowate (lamellipodia – sieć aktynowa, filopodia – równoległe wiązki), mikrokosmki jelitowe, stereocilia komórek włoskowatych ucha, transport wewnątrzkomórkowy (miozyna V – transport pęcherzyków w drożdżach i neuronach).

Filamenty pośrednie (10 nm): keratyny (komórki nabłonka, włosy, paznokcie), wimentyna (komórki mezenchymatyczne, fibroblasty), desmina (mięśnie), neurofilamenty (neurony), laminy jądrowe (blaszka jądrowa – podpora otoczki jądrowej, fosforylacja lamin podczas profazy → rozpad otoczki). Wytrzymałość mechaniczna, nie są spolaryzowane, nie uczestniczą w ruchu.

Mikrotubule (25 nm): polimeryzacja α- i β-tubuliny (heterodimer, wiąże GTP) → protofilamenty (13 protofilamentów tworzy cylinder). Spolaryzowane (koniec plus – szybka polimeryzacja/depolimeryzacja, β-tubulina; koniec minus – wolniejsza, α-tubulina; centrosom/MOTC przy końcu minus). Niestabilność dynamiczna – naprzemienne fazy wzrostu (GTP-capped) i katastrofy (hydroliza GTP → depolimeryzacja). Funkcje: wrzeciono podziałowe (mikrotubule kinetochorowe – przyczepiają się do kinetochoru na centromerze; polarne – przeciwległe bieguny, rozsuwają wrzeciono; astralne – kontakt z błoną, pozycjonowanie wrzeciona), transport wewnątrzkomórkowy (szyny dla białek motorycznych – kinezyna transport do plus-końca/obwodu, dyneina do minus-końca/centrosomu), rzęski i wici (aksonema 9+2 – 9 dubletów mikrotubul na obwodzie + 2 pojedyncze w centrum, ramiona dyneinowe, białka neksyny, mostki radialne). Centrosom – główna organizacja mikrotubul (MOTC), zawiera parę centrioli (9+0, 9 trypletów mikrotubul, brak centralnej pary) ułożonych prostopadle, otoczonych macierzą pericentriolarną (γ-tubulina – zarodkowanie polimeryzacji).

Ściana komórkowa – ochrona i wsparcie mechaniczne komórki roślinnej:
Budowa: celuloza (mikrofibryle – łańcuchy β-1,4-glukozy, syntetyzowane przez kompleks syntazy celulozowej w błonie komórkowej – rozeta terminalna), hemicelulozy (ksyloglukany – łączą mikrofibryle celulozowe), pektyny (polisacharydy kwaśne – kwas galakturonowy, w blaszce środkowej; nadają elastyczność), glikoproteiny strukturalne (ekstensyna). Warstwy: blaszka środkowa (łączy sąsiednie komórki, głównie pektyny), ściana pierwotna (cienka, elastyczna, rośnie z komórką), ściana wtórna (odkładana po zakończeniu wzrostu, grubsza, często zdrewniała – lignina nadaje sztywność, w komórkach przewodzących drewna, włóknach sklerenchymatycznych). Plazmodesmy – kanały przez ścianę, łączą protoplasty (symplast), przez które przechodzi ER (desmotubula), umożliwiają transport substancji i komunikację międzykomórkową u roślin. Jamki – cienkie miejsca w ścianie wtórnej dla transportu między komórkami.

Wakuola roślinna: otoczona pojedynczą błoną (tonoplast), zajmuje do 90% objętości dojrzałej komórki. Sok komórkowy – wodny roztwór jonów (K+, Cl-), cukrów (sacharoza, glukoza), kwasów organicznych (jabłkowy, cytrynowy, szczawiowy), aminokwasów, flawonoidów (antocyjany – czerwony, niebieski, fioletowy kolor kwiatów i owoców), alkaloidów (obrona przed roślinożercami), enzymów hydrolitycznych, kryształów (szczawian wapnia – rafidy, druzy, styloidy). Funkcje: utrzymanie turgoru (ciśnienie hydrostatyczne ~0,5-1,5 MPa), wzrost wydłużeniowy (poluzowanie ściany + napór turgoru), magazynowanie i detoksykacja (sekwestracja metali ciężkich, herbicydów), trawienie (podobne do lizosomów – hydrolazy), sygnalizacja (uwalnianie Ca2+).

PODZIAŁY KOMÓRKOWE – CYKL KOMÓRKOWY:
Fazy cyklu: G1 (wzrost, synteza białek i organelli, punkt restrykcyjny R – decyzja o wejściu w cykl podziałowy), S (replikacja DNA – podwojenie chromatyny, każdy chromosom zawiera teraz 2 chromatydy siostrzane połączone kohezyną w centromerze), G2 (wzrost, synteza białek wrzeciona, kontrola replikacji), M (mitoza – podział jądra + cytokineza). Komórki, które nie wchodzą w cykl, znajdują się w fazie G0 (spoczynkowa – neurony, kardiomiocyty). Regulacja cyklu: kinazy zależne od cyklin (Cdk) – aktywność regulowana przez cykliny (G1-cyklina/Cdk → przejście G1→S; mitotyczna cyklina/Cdk → G2→M). Punkty kontrolne: G1/S (czy DNA jest nieuszkodzone? czy warunki są sprzyjające?), G2/M (czy całe DNA jest zreplikowane? czy nie ma uszkodzeń?), M (wrzeciono podziałowe – czy wszystkie kinetochory są przyłączone?). Białko p53 – strażnik genomu, w razie uszkodzenia DNA aktywuje p21 (inhibitor Cdk) → zatrzymanie cyklu i naprawa lub apoptoza. Mutacja p53 – w >50% nowotworów człowieka.

Mitoza (szczegółowe etapy):
Profaza: kondensacja chromatyny (kondensyny) → widoczne chromosomy (każdy składa się z 2 chromatyd siostrzanych połączonych w centromerze). Fosforylacja lamin jądrowych → rozpad otoczki jądrowej (fragmenty otoczki tworzą pęcherzyki). Rozpad jąderka. Centrosomy (zduplikowane w S/G2) rozchodzą się do przeciwległych biegunów – formowanie wrzeciona podziałowego (mikrotubule astralne, polarne/interpolarne, kinetochorowe).
Prometafaza: błona jądrowa całkowicie rozproszona. Mikrotubule wrzeciona kontaktują się z kinetochorami na centromerach (dwukierunkowe przyłączenie – jedna chromatyda siostrzana do jednego bieguna). Chromosomy wykonują ruchy kongresyjne (przesuwanie do płaszczyzny równikowej).
Metafaza: maksymalna kondensacja chromosomów. Chromosomy ułożone w płaszczyźnie równikowej (płytka metafazowa). Wszystkie kinetochory przyłączone do włókien wrzeciona (spełniony punkt kontrolny M). Kolchicyna i winkrystyna – inhibitory polimeryzacji mikrotubul, zatrzymują mitozę w metafazie (stosowane do badania kariotypu). Taksol (paklitaksel) – stabilizuje mikrotubule, blokuje podział.
Anafaza (najkrótsza faza, kilka minut): A – rozdzielenie chromatyd (przecięcie kohezyny przez separazę – wcześniej hamowaną przez sekurynę; aktywacja przez kompleks promujący anafazę APC/C → ubikwitynacja sekuryny → degradacja → uwolnienie separazy). Skrócenie mikrotubul kinetochorowych (depolimeryzacja na obu końcach) → chromatydy wędrują do biegunów. B – rozchodzenie się biegunów wrzeciona (wydłużanie mikrotubul polarnych, napędzane przez kinezynę-5/BimC/Eg5).
Telofaza: chromatydy (teraz chromosomy potomne) docierają do biegunów → dekondensacja chromatyny. Odtworzenie otoczki jądrowej (defosforylacja lamin) i jąderka (transkrypcja rRNA wznowiona). Wrzeciono podziałowe zanika.
Cytokineza: zwierzęta – pierścień kurczliwy (aktyna + miozyna II) pod błoną w płaszczyźnie równikowej, tworzy bruzdę podziałową, zaciska się → dwie komórki potomne. Rośliny – fragmoplast (pozostałości wrzeciona + pęcherzyki Golgiego z pektynami i hemicelulozami) tworzy płytkę komórkową (primordialną ścianę), od środka ku obwodowi, która łączy się z istniejącą ścianą.
Efekt mitozy: 2 komórki potomne 2n, genetycznie identyczne z macierzystą (brak rekombinacji).

Mejoza – szczegółowy mechanizm:
Mejoza I (redukcyjna – redukcja liczby chromosomów 2n→n):
Profaza I (najdłuższa faza, 90% czasu mejozy):
- Leptoten: kondensacja chromatyny, chromosomy stają się widoczne jako cienkie nici, siostrzane chromatydy ściśle zespolone (kohezyna).
- Zygoten: synapsa – homologi rozpoznają się i łączą w pary (biwalenty). Kompleks synaptemalny (białkowy ruszt łączący homologi w osi) – białka SYCP1-3, umożliwia precyzyjne parowanie.
- Pachyten: crossing-over – wymiana odcinków między chromatydami niesiostrzanymi homologów. Rekombinaza Spo11 → dwuniciowe pęknięcia DNA → naprawa z wykorzystaniem chromatydy niesiostrzanej jako matrycy → rekombinacja homologiczna. Każdy crossing-over daje 1 chiazmę. Powstaje kompleks czterech chromatyd (tetrada). Średnio 2-3 crossing-overy na chromosom u człowieka.
- Diploten: rozpad kompleksu synaptemalnego, homologi zaczynają się rozchodzić, ale pozostają połączone w miejscach crossing-over – chiazmy (widoczne w mikroskopie). U samic człowieka (oogeneza) – zatrzymanie na diplotenie do owulacji (może trwać dekady – im starsza kobieta, tym większe ryzyko nondysjunkcji).
- Diakineza: terminalizacja chiazm (przesuwanie się ku końcom chromosomów), maksymalna kondensacja, zanik otoczki jądrowej i jąderka.
Metafaza I: biwalenty układają się w płaszczyźnie równikowej. Kinetochory siostrzane każdego homologu łączą się z mikrotubulami z tego samego bieguna (ko-orientacja). Losowe ułożenie biwalentów (każda para niezależnie) – podstawa II prawa Mendla.
Anafaza I: rozpad chiazm, homologi rozchodzą się do przeciwległych biegunów (segregacja chromosomów homologicznych). Redukcja liczby chromosomów 2n→n. Chromatydy siostrzane pozostają połączone w centromerze (kohezyna chroniona przez białko shugoshin).
Telofaza I: chromosomy docierają do biegunów, w wielu organizmach następuje krótka cytokineza i interfaza (bez replikacji DNA!).

Mejoza II (ekwacyjna – podział podobny do mitozy, ale bez replikacji DNA):
Profaza II: kondensacja, zanik otoczki jądrowej (jeśli się odtworzyła), formowanie wrzeciona.
Metafaza II: chromosomy (każdy z 2 chromatyd) układają się w płytce metafazowej. Kinetochory siostrzane przyłączone do przeciwnych biegunów (bi-orientacja).
Anafaza II: degradacja kohezyny centromerowej → rozdzielenie chromatyd siostrzanych → przemieszczenie do biegunów.
Telofaza II + cytokineza → 4 komórki potomne n.
Efekt mejozy: 4 haploidalne (n) komórki, zróżnicowane genetycznie dzięki: crossing-over w profazie I (wymiana odcinków między niesiostrzanymi chromatydami – nowe kombinacje alleli na chromosomach), losowemu rozchodzeniu się chromosomów homologicznych w anafazie I (2²³ ≈ 8,4 miliona możliwych kombinacji u człowieka), losowemu łączeniu się gamet podczas zapłodnienia (dodatkowe 2²³ × 2²³ ≈ 70 bilionów kombinacji – źródło ogromnej zmienności genetycznej).

Gametogeneza u człowieka:
Spermatogeneza (jądra, kanaliki nasienne): spermatogonium 2n → (mitoza) → spermatocyt I rzędu 2n → (mejoza I) → 2 spermatocyty II rzędu n → (mejoza II) → 4 spermatydy n → (spermiogeneza – kondensacja jądra, formowanie akrosomu i wici) → 4 plemniki. Ciągła od pokwitania przez całe życie. ~1000 plemników/s, ~100-300 mln/ejakulat.
Oogeneza (jajniki): oogonium 2n → (mitoza, tylko w życiu płodowym) → oocyt I rzędu 2n (zatrzymanie na diplotenie profazy I – do owulacji) → (mejoza I – ukończona tuż przed owulacją, nierówny podział!) → 1 oocyt II rzędu n + 1 ciałko kierunkowe (polocyt) → (mejoza II – ukończona po zapłodnieniu) → 1 komórka jajowa n + 1 ciałko kierunkowe. Nierównomierne podziały – oocyt zachowuje całą cytoplazmę i organelle (szczególnie mitochondria). Kobieta rodzi się z ~1-2 mln oocytów, w okresie rozrodczym dojrzewa ~400-500."""

# Write the expanded biology file header
print("Biology expansion content prepared.")
print(f"Cytologia block: {len(BIOLOGY_EXPANDED_CYTOLOGIA)} characters")
